import type { Subject } from '../types'
import {
  addStep,
  balloonNumberStep,
  balloonStep,
  compareStep,
  countOnStep,
  countStep,
  makeTenStep,
  numberChoices,
  numberLineStep,
  orderStep,
  patternStep,
  pizzaStep,
  raceAddStep,
  raceStep,
  repeat,
  shapeStep,
  shuffle,
  sid,
  sortStep,
  subStep,
  tapCountStep,
  teach,
  teachAdd,
  teachCount,
  teachShape,
  teachSub,
  wordChoices,
} from './builders'

export const math: Subject = {
  id: 'math',
  name: 'Math',
  icon: 'numbers',
  tagline: 'Counting, adding and shapes',
  tone: 'sun',
  strands: ['Counting & Place Value', 'Addition', 'Subtraction', 'Shapes & Patterns'],
  units: [
    /* ================= UNIT 1 ================= */
    {
      id: 'm-numbers',
      title: 'Numbers to 20',
      icon: 'balloon',
      tone: 'sun',
      lessons: [
        {
          id: 'm-count-10',
          title: 'Count to 10',
          icon: 'ten',
          blurb: 'Count things one by one',
          tone: 'sun',
          teach: [
            teach('Counting is easy!', 'Counting means saying the numbers in order, one for each thing. Watch me count my apples!', 'apple'),
            teachCount('apple', 3, 'apple'),
            teachCount('star', 5, 'star'),
          ],
          steps: [
            {
              ...tapCountStep('balloon', 8, 4, { prompt: 'Tap 4 balloons!' }),
              explain: 'You tapped 4 balloons. Counting one at a time keeps you on track.',
            },
            balloonNumberStep(4, { max: 8, matches: 3 }),
            countStep('apple', 3),
            countStep('bee', 5),
            balloonNumberStep(7, { max: 10, matches: 3 }),
            {
              ...tapCountStep('cookie', 7, 6, { prompt: 'Give the bunny 6 cookies!' }),
              explain: 'The bunny wanted 6 cookies — you counted them out!',
            },
            numberLineStep(6, 1, 10, { prompt: 'Tap the number 6.' }),
            pizzaStep('Ruby', [
              { icon: 'mushroom', name: 'mushroom' },
              { icon: 'cheese', name: 'cheese' },
            ]),
            countStep('star', 9),
            {
              ...tapCountStep('butterfly', 10, 10, { prompt: 'Tap every butterfly!' }),
              explain: 'Ten butterflies, ten taps. You counted to 10!',
            },
          ],
        },
        {
          id: 'm-count-20',
          title: 'Count to 20',
          icon: 'balloon',
          blurb: 'Bigger groups, all the way to 20',
          tone: 'sun',
          teach: [
            teach('Ten and more!', 'After ten comes eleven, then twelve, all the way to twenty! The teen numbers all start with a one.', 'balloon'),
            teachCount('balloon', 12, 'balloon'),
            teach('Two rows of ten', 'Two full rows of ten balloons make twenty. Ten and ten more!', 'yellowBall', '10 + 10 = 20'),
          ],
          steps: [
            countStep('balloon', 12, 4),
            balloonNumberStep(12, { max: 16, matches: 3 }),
            numberLineStep(14, 10, 20),
            countStep('ladybug', 15, 5),
            {
              id: sid('teen'),
              kind: 'choice',
              prompt: 'Which number comes right after 16?',
              say: 'Which number comes right after sixteen?',
              hint: 'Say the numbers in order: 15, 16, 17…',
              explain: 'After 16 comes 17. The teen numbers go up by one each time.',
              options: numberChoices(17, { count: 3, min: 10, max: 21 }),
            },
            countStep('grapes', 18, 5),
            {
              id: sid('twenty'),
              kind: 'choice',
              prompt: 'How many is this? Two full rows of ten!',
              say: 'Two full rows of ten. How many is that?',
              hint: 'Count by tens: 10, 20.',
              explain: 'Two groups of ten make 20.',
              visual: { kind: 'icons', items: [...repeat('yellowBall', 10), ...repeat('blueBall', 10)], layout: 'grid', size: 'md' },
              options: numberChoices(20, { count: 3, min: 12, max: 24 }),
            },
            countStep('turtle', 20, 4),
          ],
        },
        {
          id: 'm-number-line',
          title: 'Number Line Hop',
          icon: 'rabbit',
          blurb: 'Hop along and find the number',
          tone: 'sun',
          teach: [
            teach('The number line', 'A number line is a path with numbers in order. The rabbit hops one number at a time, left to right!', 'rabbit'),
            teach('Bigger means further', 'Numbers get bigger as you hop to the right. Five is further along than three!', 'star'),
          ],
          steps: [
            numberLineStep(5, 1, 10, { prompt: 'Hop to the number 5!' }),
            numberLineStep(9, 1, 10, { prompt: 'Hop to the number 9!' }),
            balloonNumberStep(14, { max: 18, matches: 2 }),
            numberLineStep(14, 10, 20, { prompt: 'Hop to the number 14!' }),
            numberLineStep(18, 10, 20, { prompt: 'Hop to the number 18!' }),
            numberLineStep(11, 8, 16, { prompt: 'Tap the number that comes after 10.' }),
            countOnStep(12, 1, 'rabbit'),
            countOnStep(16, -1, 'carrot'),
          ],
        },
        {
          id: 'm-before-after',
          title: 'Before & After',
          icon: 'skip',
          blurb: 'One more, one less',
          tone: 'sun',
          teach: [
            teach('Before and after', 'Every number has a neighbour before it and after it. Before five comes four. After five comes six!', 'skip'),
            teach('One more, one less', 'One more is a hop forward. One less is a hop back. Count with me: one, two, three!', 'sunHappy'),
          ],
          steps: [
            countOnStep(5, 1, 'apple'),
            countOnStep(9, 1, 'cookie'),
            countOnStep(15, 1, 'star'),
            countOnStep(8, -1, 'fish'),
            countOnStep(12, -1, 'bee'),
            numberLineStep(11, 8, 16, { prompt: 'Tap the number that comes after 10.' }),
            {
              id: sid('mid'),
              kind: 'choice',
              prompt: 'Which number is missing?',
              say: 'Which number is missing? 7, 8, blank, 10.',
              hint: 'Count from 7 out loud.',
              explain: 'The missing number is 9 — it sits right between 8 and 10.',
              visual: { kind: 'word', words: ['7', '8', '?', '10'], caption: 'What is missing?' },
              options: numberChoices(9, { count: 3, min: 5, max: 13 }),
            },
          ],
        },
        {
          id: 'm-more-fewer',
          title: 'More or Fewer',
          icon: 'scale',
          blurb: 'Which group is bigger?',
          tone: 'sun',
          teach: [
            teach('More means bigger', 'The group with more things is the bigger group. Count both sides to find out!', 'scale'),
            teach('Fewer means smaller', 'The group with fewer things is the smaller group. Three cookies are fewer than five cookies!', 'cookie'),
          ],
          steps: [
            compareStep(5, 3, 'apple', 'cookie', 'more'),
            compareStep(4, 7, 'fish', 'star', 'more'),
            compareStep(6, 9, 'balloon', 'bee', 'fewer'),
            {
              id: sid('cmp-num'),
              kind: 'choice',
              prompt: 'Which number is bigger?',
              say: 'Which number is bigger, 14 or 9?',
              hint: 'Teen numbers are always bigger than single digits.',
              explain: '14 is bigger than 9 because 14 has a tens digit.',
              visual: { kind: 'word', words: ['14', 'vs', '9'] },
              options: numberChoices(14, { count: 2, min: 9, max: 15, decoys: [9] }),
            },
            compareStep(8, 6, 'donut', 'grapes', 'more'),
            {
              id: sid('equal'),
              kind: 'choice',
              prompt: 'Do these two groups have the same number?',
              say: 'Do these two groups have the same number?',
              hint: 'Count each group, then compare.',
              explain: 'Both groups have 4. When two numbers match, they are equal!',
              visual: {
                kind: 'groups',
                groups: [
                  { icons: repeat('greenBall', 4), label: '4' },
                  { icons: repeat('orangeBall', 4), label: '4' },
                ],
              },
              options: wordChoices('Yes, the same!', ['No, different']),
            },
          ],
        },
      ],
    },

    /* ================= UNIT 2 ================= */
    {
      id: 'm-add',
      title: 'Adding',
      icon: 'plusBadge',
      tone: 'grass',
      lessons: [
        {
          id: 'm-add-10',
          title: 'Add Within 10',
          icon: 'plusBadge',
          blurb: 'Put two groups together',
          tone: 'grass',
          teach: [
            teach('Adding puts groups together', 'Adding means putting two groups together and counting them all!', 'plusBadge'),
            teachAdd(2, 3, 'apple', 'apple'),
            teachAdd(4, 1, 'bee', 'bee'),
          ],
          steps: [
            addStep(2, 3, 'apple'),
            raceAddStep(2, 3),
            addStep(4, 1, 'bee'),
            {
              ...addStep(5, 3, 'cookie'),
              explain: '5 and 3 make 8. Count them all together to check!',
            },
            {
              id: sid('add-tap'),
              kind: 'tapCount',
              prompt: 'Tap 3 red dots, then 4 blue dots. How many all together?',
              say: 'Tap every dot. How many all together?',
              hint: 'Count every dot you tap.',
              explain: '3 and 4 make 7 dots.',
              visual: { kind: 'icons', items: [...repeat('redBall', 3), ...repeat('blueBall', 4)], layout: 'row', size: 'lg' },
              target: 7,
            },
            addStep(6, 2, 'star'),
            raceAddStep(4, 4),
            makeTenStep(7),
          ],
        },
        {
          id: 'm-add-20',
          title: 'Add Within 20',
          icon: 'abacus',
          blurb: 'Add with two full tens',
          tone: 'grass',
          teach: [
            teach('Ten makes it easy', 'When you add to ten, the ones just keep going: eleven, twelve, thirteen!', 'abacus'),
            teachAdd(10, 4, 'strawberry', 'strawberry'),
            teachAdd(9, 8, 'fish', 'fish'),
          ],
          steps: [
            {
              id: sid('a1'),
              kind: 'choice',
              prompt: 'How many in all?',
              say: 'Ten plus four. How many in all?',
              hint: 'When you add to 10, the ones just grow: 11, 12, 13…',
              explain: '10 + 4 = 14. Adding to ten makes a teen number.',
              visual: {
                kind: 'equation',
                parts: [{ text: '10' }, { text: '+' }, { icons: repeat('strawberry', 4) }, { text: '=' }, { text: '?' }],
              },
              options: numberChoices(14, { count: 3, min: 11, max: 17 }),
            },
            addStep(8, 5, 'donut', { max: 16 }),
            addStep(7, 6, 'ladybug', { max: 16 }),
            {
              ...addStep(9, 8, 'fish', { max: 20 }),
              hint: 'Make 10 first: 9 + 1 = 10, then add what is left.',
              explain: '9 + 8 = 17. Trick: 9 + 8 is like 10 + 7, because 9 borrowed 1 from the 8!',
            },
            makeTenStep(8, 20),
            raceAddStep(9, 8),
            addStep(6, 6, 'star', { max: 15 }),
            addStep(10, 10, 'balloon', { max: 24 }),
          ],
        },
        {
          id: 'm-make-ten',
          title: 'Make 10',
          icon: 'ten',
          blurb: 'The magic number 10',
          tone: 'grass',
          teach: [
            teach('Ten is magic!', 'Ten is a magic number in math. Lots of pairs of numbers snap together to make ten!', 'ten'),
            teachAdd(6, 4, 'redBall', 'ball'),
            teachAdd(3, 7, 'blueBall', 'ball'),
          ],
          steps: [
            makeTenStep(6),
            makeTenStep(3),
            raceAddStep(6, 4),
            makeTenStep(9),
            makeTenStep(5),
            {
              id: sid('tenframe2'),
              kind: 'choice',
              prompt: 'Look at the ten-frame. How many more to make 10?',
              say: 'How many more to fill the ten frame?',
              hint: 'Count the empty boxes.',
              explain: '7 are filled, so 3 more fill it up. 7 + 3 = 10!',
              visual: { kind: 'tenframe', filled: 7 },
              options: numberChoices(3, { count: 3, min: 0, max: 8 }),
            },
            {
              id: sid('fact'),
              kind: 'choice',
              prompt: 'Which pair of numbers makes 10?',
              say: 'Which pair of numbers makes ten?',
              hint: 'Add each pair in your head.',
              explain: '6 + 4 = 10. Those two are number partners!',
              options: shuffle([
                { id: sid('o'), text: '6 + 4', correct: true },
                { id: sid('o'), text: '6 + 5' },
                { id: sid('o'), text: '3 + 4' },
              ]),
            },
          ],
        },
        {
          id: 'm-add-story',
          title: 'Add Story Problems',
          icon: 'book',
          blurb: 'Stories you can see',
          tone: 'grass',
          teach: [
            teach('Stories can be math', 'A story can hide an adding problem. Listen: two birds sat on a tree, then one more came. How many now?', 'bird'),
            teachAdd(2, 1, 'bird', 'bird'),
            teach('Find the numbers', 'When you hear a story, find the two numbers, then add them together!', 'book'),
          ],
          steps: [
            {
              ...addStep(3, 4, 'bird'),
              prompt: '3 birds are on a tree. 4 more fly in. How many birds now?',
              say: 'Three birds sit on a tree. Four more fly in. How many birds now?',
              explain: '3 birds plus 4 birds make 7 birds.',
            },
            {
              ...addStep(5, 2, 'pizza'),
              prompt: 'There are 5 pizza slices. Dad brings 2 more. How many now?',
              say: 'There are five pizza slices. Dad brings two more. How many now?',
              explain: '5 slices plus 2 slices make 7 slices.',
            },
            {
              ...addStep(6, 3, 'car'),
              prompt: '6 cars are parked. 3 more come. How many cars?',
              say: 'Six cars are parked. Three more come. How many cars?',
              explain: '6 cars plus 3 cars make 9 cars.',
            },
            {
              ...addStep(4, 4, 'teddy'),
              prompt: '4 bears sit on a shelf. 4 more jump up. How many bears?',
              say: 'Four bears sit on a shelf. Four more jump up. How many bears?',
              explain: '4 plus 4 makes 8.',
            },
            {
              ...addStep(8, 2, 'balloon'),
              prompt: 'You have 8 balloons. You get 2 more. How many balloons?',
              say: 'You have eight balloons. You get two more. How many balloons?',
              explain: '8 + 2 = 10. That makes a perfect ten!',
            },
            {
              ...addStep(7, 5, 'fish'),
              prompt: '7 fish swim in a tank. 5 more join them. How many fish?',
              say: 'Seven fish swim in a tank. Five more join. How many fish?',
              explain: '7 + 5 = 12. Split the 5 into 3 and 2 to make ten first!',
            },
            /* baking a pizza = adding toppings: 2 mushrooms + 2 peppers = 4 toppings! */
            pizzaStep('Max', [
              { icon: 'mushroom', name: 'mushroom' },
              { icon: 'pepper', name: 'pepper' },
            ], {
              each: 2,
              prompt: "Make Max's pizza: 2 mushrooms and 2 peppers — how many toppings in all?",
              say: 'I am Max! I want two mushrooms and two peppers on my pizza. How many toppings is that in all?',
              explain: '2 mushrooms and 2 peppers make 4 toppings in all. 2 + 2 = 4!',
            }),
          ],
        },
      ],
    },

    /* ================= UNIT 3 ================= */
    {
      id: 'm-sub',
      title: 'Subtracting',
      icon: 'minus',
      tone: 'sky',
      lessons: [
        {
          id: 'm-sub-10',
          title: 'Subtract Within 10',
          icon: 'minus',
          blurb: 'Take some away',
          tone: 'sky',
          teach: [
            teach('Subtracting takes away', 'Subtracting means taking some away and counting what is left!', 'minus'),
            teachSub(5, 2, 'apple', 'apple'),
            teachSub(7, 3, 'cookie', 'cookie'),
          ],
          steps: [
            subStep(5, 2, 'apple'),
            raceStep('5 − 2 = ?', 3, [4, 2], {
              say: 'Five take away two. Drive to the answer!',
              explain: '5 take away 2 leaves 3. Vroom!',
            }),
            subStep(7, 3, 'cookie'),
            {
              id: sid('sub-tap'),
              kind: 'choice',
              prompt: 'Cross out 4. How many are left?',
              say: 'Four are taken away. How many are left?',
              hint: 'Count the ones that are NOT crossed out.',
              explain: '9 take away 4 leaves 5.',
              visual: {
                kind: 'equation',
                parts: [{ icons: repeat('ladybug', 9) }, { text: '−' }, { icons: repeat('ladybug', 4), faded: true }, { text: '=' }, { text: '?' }],
              },
              options: numberChoices(5, { count: 3, min: 0, max: 9 }),
            },
            subStep(8, 8, 'star'),
            subStep(10, 6, 'balloon'),
            subStep(6, 1, 'fish'),
            {
              id: sid('sub-zero'),
              kind: 'choice',
              prompt: 'What happens when you take away nothing?',
              say: 'Five take away zero. What is left?',
              hint: 'Taking away nothing changes nothing.',
              explain: '5 − 0 = 5. Taking away zero always leaves the same number!',
              visual: { kind: 'equation', parts: [{ text: '5' }, { text: '−' }, { text: '0' }, { text: '=' }, { text: '?' }] },
              options: numberChoices(5, { count: 3, min: 0, max: 9 }),
            },
          ],
        },
        {
          id: 'm-sub-20',
          title: 'Subtract Within 20',
          icon: 'downTriangle',
          blurb: 'Bigger numbers, same idea',
          tone: 'sky',
          teach: [
            teach('Big numbers, same trick', 'Subtracting big numbers works the same way: take away, then count what is left!', 'downTriangle'),
            teachSub(15, 5, 'grapes', 'grapes'),
            teachSub(18, 6, 'bee', 'bee'),
          ],
          steps: [
            subStep(14, 4, 'grapes'),
            {
              id: sid('s-teen'),
              kind: 'choice',
              prompt: 'How many are left?',
              say: 'Fifteen take away five. How many are left?',
              hint: 'Take away the ones. What is left is a full ten.',
              explain: '15 − 5 = 10. Taking the ones leaves a whole ten!',
              visual: { kind: 'equation', parts: [{ text: '15' }, { text: '−' }, { text: '5' }, { text: '=' }, { text: '?' }] },
              options: numberChoices(10, { count: 3, min: 5, max: 15 }),
            },
            subStep(18, 6, 'bee'),
            subStep(12, 3, 'strawberry'),
            {
              ...subStep(16, 9, 'turtle'),
              hint: 'Count back 9 from 16. Or take away 6 first to reach 10, then 3 more.',
              explain: '16 − 9 = 7. Take away 6 to get to 10, then take 3 more.',
            },
            raceStep('20 − 10 = ?', 10, [9, 11], {
              say: 'Twenty take away ten. Drive to the answer!',
              explain: '20 take away 10 leaves a perfect 10!',
            }),
            numberLineStep(13, 10, 20, { prompt: 'Start at 16 and count back 3. Tap where you land.' }),
          ],
        },
        {
          id: 'm-how-many-more',
          title: 'How Many More?',
          icon: 'magnifier',
          blurb: 'Find the difference',
          tone: 'sky',
          teach: [
            teach('Match them up!', 'To find how many more, match the two groups one by one. The ones left without a partner are the answer!', 'magnifier'),
            teachSub(7, 4, 'apple', 'apple'),
            teach('Subtract to compare', 'How many more means subtract! The bigger number take away the smaller number tells you the difference.', 'scale'),
          ],
          steps: [
            {
              id: sid('hmm1'),
              kind: 'choice',
              prompt: 'How many more apples than bananas?',
              say: 'How many more apples than bananas?',
              hint: 'Match them up one by one. The extras are the answer.',
              explain: '7 apples and 4 bananas. 3 apples have no partner, so 7 − 4 = 3.',
              visual: {
                kind: 'groups',
                groups: [
                  { icons: repeat('apple', 7), label: 'apple 7' },
                  { icons: repeat('banana', 4), label: 'banana 4' },
                ],
              },
              options: numberChoices(3, { count: 3, min: 0, max: 7 }),
            },
            {
              id: sid('hmm2'),
              kind: 'choice',
              prompt: 'How many fewer dogs than cats?',
              say: 'How many fewer dogs than cats?',
              hint: 'Count the cats, count the dogs, then subtract.',
              explain: '9 cats and 6 dogs. 9 − 6 = 3, so there are 3 fewer dogs.',
              visual: {
                kind: 'groups',
                groups: [
                  { icons: repeat('cat', 9), label: 'cat 9' },
                  { icons: repeat('dog', 6), label: 'dog 6' },
                ],
              },
              options: numberChoices(3, { count: 3, min: 0, max: 9 }),
            },
            {
              ...subStep(10, 7, 'blossom'),
              prompt: '10 flowers. 7 are picked. How many are still growing?',
              say: 'Ten flowers. Seven are picked. How many are still growing?',
            },
            {
              id: sid('hmm3'),
              kind: 'choice',
              prompt: 'I have 5 stickers. You have 5. How many more do you need to have 5 more than me?',
              say: 'We both have five stickers. How many more do you need to have five more than me?',
              hint: 'You need your 5, plus 5 more.',
              explain: 'To have 5 more than 5, you need 10.',
              visual: { kind: 'word', words: ['5', '+', '5', '=', '?'] },
              options: numberChoices(10, { count: 3, min: 5, max: 15 }),
            },
            subStep(15, 5, 'balloon'),
          ],
        },
      ],
    },

    /* ================= UNIT 4 ================= */
    {
      id: 'm-shapes',
      title: 'Shapes, Patterns & Place Value',
      icon: 'diamond',
      tone: 'berry',
      lessons: [
        {
          id: 'm-2d-shapes',
          title: '2D Shapes',
          icon: 'diamond',
          blurb: 'Circles, squares and more',
          tone: 'berry',
          teach: [
            teachShape({ shape: 'circle', color: '#ffd166' }, 'This is a circle!', 'A circle is perfectly round, like a cookie or a ball. It has no corners at all!'),
            teachShape({ shape: 'triangle', color: '#3ddc84' }, 'This is a triangle!', 'A triangle has three sides and three corners. Like a slice of pizza!'),
            teachShape({ shape: 'square', color: '#2ec9f5' }, 'This is a square!', 'A square has four sides, and they are all the same length.'),
          ],
          steps: [
            shapeStep({ shape: 'circle', color: '#ffc93c' }, [
              { shape: 'square', color: '#33c4ff' },
              { shape: 'triangle', color: '#34d399' },
            ], 'A circle is perfectly round with no corners.'),
            shapeStep({ shape: 'triangle', color: '#ff5fa2' }, [
              { shape: 'circle', color: '#ffc93c' },
              { shape: 'rectangle', color: '#9b5cff' },
            ], 'A triangle has 3 sides and 3 corners.'),
            shapeStep({ shape: 'square', color: '#33c4ff' }, [
              { shape: 'rectangle', color: '#ff7a59' },
              { shape: 'oval', color: '#34d399' },
            ], 'A square has 4 equal sides and 4 corners.'),
            {
              id: sid('sh-sides'),
              kind: 'choice',
              prompt: 'How many sides does a square have?',
              say: 'How many sides does a square have?',
              hint: 'Count each straight side, going around the shape.',
              explain: 'A square has 4 sides and 4 corners.',
              visual: { kind: 'shapes', shapes: [{ shape: 'square', color: '#33c4ff', size: 130 }] },
              options: numberChoices(4, { count: 3, min: 2, max: 7 }),
            },
            shapeStep({ shape: 'rectangle', color: '#ff7a59' }, [
              { shape: 'square', color: '#33c4ff' },
              { shape: 'circle', color: '#ffc93c' },
            ], 'A rectangle has 4 sides, but two are long and two are short.'),
            {
              id: sid('sh-sort'),
              kind: 'choice',
              prompt: 'Which one has 6 sides?',
              say: 'Which shape has six sides?',
              hint: 'Count the sides of each shape.',
              explain: 'A hexagon has 6 sides.',
              options: shuffle([
                { id: sid('o'), shape: { shape: 'hexagon', color: '#9b5cff' }, caption: 'hexagon', correct: true },
                { id: sid('o'), shape: { shape: 'triangle', color: '#34d399' }, caption: 'triangle' },
                { id: sid('o'), shape: { shape: 'square', color: '#33c4ff' }, caption: 'square' },
              ]),
            },
            shapeStep({ shape: 'heart', color: '#ff5fa2' }, [
              { shape: 'star', color: '#ffc93c' },
              { shape: 'diamond', color: '#9b5cff' },
            ], 'A heart has a point at the bottom and two bumps on top.'),
            /* shape-word hunt: read the word on each balloon, then pop! */
            balloonStep('circle', ['circle', 'circle', 'circle', 'square', 'triangle', 'heart', 'star', 'diamond'], {
              prompt: 'Pop every balloon with the word CIRCLE!',
              say: 'Pop every balloon with the word circle on it!',
              matches: 3,
              explain: 'You found every balloon with the word circle — c-i-r-c-l-e!',
            }),
          ],
        },
        {
          id: 'm-patterns',
          title: 'Patterns',
          icon: 'puzzle',
          blurb: 'What comes next?',
          tone: 'berry',
          teach: [
            teach('Patterns repeat!', 'A pattern is a rule that repeats over and over. Red ball, blue ball, red ball, blue ball… what comes next? Blue!', 'redBall'),
            teach('Say it out loud', 'Saying a pattern out loud helps you hear what comes next. Try it: star, moon, star, moon, star… moon!', 'star'),
          ],
          steps: [
            patternStep(['redBall', 'blueBall'], 2, 'greenBall'),
            patternStep(['star', 'moon'], 2, 'sun'),
            patternStep(['apple', 'apple', 'banana'], 2, 'grapes'),
            {
              id: sid('pat-shape'),
              kind: 'choice',
              prompt: 'What comes next in the pattern?',
              say: 'What comes next in the pattern?',
              hint: 'Look at the repeating part.',
              explain: 'The pattern goes purple, yellow, purple, yellow… so purple is next.',
              visual: {
                kind: 'shapes',
                shapes: [
                  { shape: 'circle', color: '#9b5cff', size: 56 },
                  { shape: 'circle', color: '#ffc93c', size: 56 },
                  { shape: 'circle', color: '#9b5cff', size: 56 },
                  { shape: 'circle', color: '#ffc93c', size: 56 },
                ],
                caption: 'What comes next?',
              },
              options: shuffle([
                { id: sid('o'), shape: { shape: 'circle', color: '#9b5cff', size: 64 }, correct: true },
                { id: sid('o'), shape: { shape: 'circle', color: '#ffc93c', size: 64 } },
                { id: sid('o'), shape: { shape: 'circle', color: '#34d399', size: 64 } },
              ]),
            },
            orderStep(
              'Put the growing pattern in order — smallest first!',
              [
                { icon: 'ant', label: 'tiny', order: 1 },
                { icon: 'mouse', label: 'small', order: 2 },
                { icon: 'cat', label: 'medium', order: 3 },
                { icon: 'dog', label: 'big', order: 4 },
              ],
              'Size patterns grow bigger each time: ant, mouse, cat, dog.',
            ),
            patternStep(['frog', 'frog', 'turtle'], 2, 'fish'),
          ],
        },
        {
          id: 'm-sorting',
          title: 'Sorting & Position',
          icon: 'basket',
          blurb: 'Put things in the right basket',
          tone: 'berry',
          teach: [
            teach('Sorting means grouping', 'Sorting means putting things into groups. All the red things here, all the blue things there!', 'basket'),
            teach('Pick one rule', 'Good sorting uses one rule at a time: colour, size, or shape. Look at one thing and ask, which basket does it go in?', 'puzzle'),
          ],
          steps: [
            sortStep(
              'Sort by colour!',
              [
                { id: 'red', label: 'Red', icon: 'redBall', tone: 'coral' },
                { id: 'blue', label: 'Blue', icon: 'blueBall', tone: 'sky' },
              ],
              [
                { icon: 'strawberry', label: 'strawberry', bin: 'red' },
                { icon: 'blueberry', label: 'blueberry', bin: 'blue' },
                { icon: 'apple', label: 'apple', bin: 'red' },
                { icon: 'whale', label: 'whale', bin: 'blue' },
                { icon: 'car', label: 'red car', bin: 'red' },
                { icon: 'waterDrop', label: 'water drop', bin: 'blue' },
              ],
              'Sorting by colour means looking at just one thing: the colour!',
            ),
            sortStep(
              'Sort by size!',
              [
                { id: 'big', label: 'Big', icon: 'elephant', tone: 'grape' },
                { id: 'small', label: 'Small', icon: 'ant', tone: 'grass' },
              ],
              [
                { icon: 'bus', label: 'bus', bin: 'big' },
                { icon: 'ladybug', label: 'ladybug', bin: 'small' },
                { icon: 'house', label: 'house', bin: 'big' },
                { icon: 'bee', label: 'bee', bin: 'small' },
                { icon: 'whale', label: 'whale', bin: 'big' },
                { icon: 'seed', label: 'seed', bin: 'small' },
              ],
              'A bus is big and a ladybug is small — size sorting!',
            ),
            {
              id: sid('pos1'),
              kind: 'choice',
              prompt: 'Where is the bird?',
              say: 'Look at the picture. Where is the bird?',
              hint: 'Above means higher up.',
              explain: 'The bird is above the house — it is flying up high.',
              visual: {
                kind: 'story',
                frames: [
                  { icon: 'bird', caption: 'bird' },
                  { icon: 'house', caption: 'house' },
                ],
              },
              options: wordChoices('above', ['below', 'inside']),
              layout: 'row',
            },
            {
              id: sid('pos2'),
              kind: 'choice',
              prompt: 'Tap the kitten that is UNDER the table.',
              say: 'Tap the kitten that is under the table.',
              hint: 'Under means below something else.',
              explain: 'Under means below. The kitten under the table is hiding below it.',
              options: shuffle([
                { id: sid('o'), icon: 'cat', caption: 'under the table', group: ['chair', 'cat'], correct: true },
                { id: sid('o'), icon: 'cat', caption: 'on the table', group: ['cat', 'chair'] },
              ]),
              layout: 'grid-2',
            },
            sortStep(
              'Sort: which ones are round?',
              [
                { id: 'round', label: 'Round', icon: 'blueBall', tone: 'sky' },
                { id: 'corners', label: 'Has corners', icon: 'downTriangle', tone: 'berry' },
              ],
              [
                { icon: 'ball', label: 'ball', bin: 'round' },
                { icon: 'book', label: 'book', bin: 'corners' },
                { icon: 'cookie', label: 'cookie', bin: 'round' },
                { icon: 'house', label: 'house', bin: 'corners' },
                { icon: 'fullMoon', label: 'moon', bin: 'round' },
                { icon: 'cheese', label: 'cheese', bin: 'corners' },
              ],
            ),
          ],
        },
        {
          id: 'm-place-value',
          title: 'Tens and Ones',
          icon: 'brick',
          blurb: 'How big numbers are built',
          tone: 'berry',
          teach: [
            teach('Numbers are built from tens', 'Big numbers are made of tens and ones. Fourteen is one ten and four ones!', 'brick'),
            teach('The tens place is special', 'The first digit counts tens, the second counts ones. Twenty-five is two tens and five ones.', 'abacus'),
          ],
          steps: [
            {
              id: sid('pv1'),
              kind: 'choice',
              prompt: 'How many tens and ones in 14?',
              say: 'How many tens and ones are in fourteen?',
              hint: 'The first digit is the tens, the second is the ones.',
              explain: '14 is 1 ten and 4 ones.',
              options: shuffle([
                { id: sid('o'), text: '1 ten and 4 ones', correct: true },
                { id: sid('o'), text: '4 tens and 1 one' },
                { id: sid('o'), text: '1 ten and 1 one' },
              ]),
            },
            {
              id: sid('pv2'),
              kind: 'choice',
              prompt: 'What number is 2 tens and 5 ones?',
              say: 'What number is two tens and five ones?',
              hint: '2 tens is 20. Then add 5 ones.',
              explain: '2 tens = 20, plus 5 ones = 25.',
              visual: { kind: 'tenframe', filled: 10, caption: '2 tens and 5 ones' },
              options: numberChoices(25, { count: 3, min: 20, max: 30 }),
            },
            {
              id: sid('pv3'),
              kind: 'choice',
              prompt: 'Which number is the biggest?',
              say: 'Which number is the biggest: thirty-one, thirteen, or thirty-three?',
              hint: 'Compare the tens first!',
              explain: 'Compare tens: 3 tens beats 1 ten. 33 has the most.',
              options: shuffle([
                { id: sid('o'), text: '33', correct: true },
                { id: sid('o'), text: '31' },
                { id: sid('o'), text: '13' },
              ]),
            },
            {
              id: sid('pv4'),
              kind: 'choice',
              prompt: 'What is the value of the 4 in 42?',
              say: 'What is the value of the four in forty-two?',
              hint: 'The tens place counts in tens.',
              explain: 'The 4 is in the tens place, so it means 40.',
              options: shuffle([
                { id: sid('o'), text: '40', correct: true },
                { id: sid('o'), text: '4' },
                { id: sid('o'), text: '14' },
              ]),
            },
            {
              id: sid('pv5'),
              kind: 'choice',
              prompt: 'Count by tens: 10, 20, 30, …',
              say: 'Count by tens. Ten, twenty, thirty, what comes next?',
              hint: 'Each hop adds one more ten.',
              explain: '10, 20, 30, 40 — counting by tens adds 10 each time.',
              options: numberChoices(40, { count: 3, min: 30, max: 60, decoys: [50, 31] }),
            },
            numberLineStep(50, 10, 100, { prompt: 'Tap the number 50.' }),
          ],
        },
      ],
    },
  ],
}
