import type { ChoiceStep, Subject } from '../types'
import {
  balloonStep,
  buildWordStep,
  matchStep,
  numberChoices,
  orderStep,
  pictureChoices,
  raceStep,
  shuffle,
  sid,
  storyStep,
  teach,
  wordChoices,
  wordStep,
} from './builders'

/* ---------- small helpers used only by reading ---------- */

/** "Which picture starts with B?" — the answer is a picture, not a word. */
function letterStep(
  letter: string,
  correct: { icon: string; caption: string },
  wrongs: { icon: string; caption: string }[],
): ChoiceStep {
  const L = letter.toUpperCase()
  return {
    id: sid('sound'),
    kind: 'choice',
    prompt: `Which one starts with the letter ${L}?`,
    say: `Which picture starts with the letter ${letter}? ${letter}… ${letter}…`,
    hint: `Say the sound /${letter}/ and try each picture out loud.`,
    explain: `${correct.caption} starts with ${L}. ${L} is for ${correct.caption}!`,
    visual: { kind: 'word', words: [`${L}`, `${letter}`] },
    options: pictureChoices(correct, wrongs),
    layout: 'grid-3',
  }
}

/** Same idea, but listening for the sound at the END of a word. */
function endSoundStep(
  correct: { icon: string; caption: string },
  wrongs: { icon: string; caption: string }[],
  sound: string,
): ChoiceStep {
  return {
    id: sid('endsound'),
    kind: 'choice',
    prompt: `Which one ends with the /${sound}/ sound?`,
    say: `Which picture ends with the ${sound} sound?`,
    hint: 'Say the word slowly and listen to the very last sound.',
    explain: `${correct.caption} ends with the /${sound}/ sound.`,
    options: pictureChoices(correct, wrongs),
    layout: 'grid-3',
  }
}

function sightStep(word: string, wrongs: string[]): ChoiceStep {
  return {
    id: sid('sight'),
    kind: 'choice',
    prompt: `Tap the word "${word}".`,
    say: `Tap the word… ${word}.`,
    hint: 'Look at the first letter and the shape of the whole word.',
    explain: `We know "${word}" by sight — it is a word we see all the time.`,
    options: wordChoices(word, wrongs),
    layout: 'row',
  }
}

function syllableStep(icon: string, name: string, answer: number, wrongs: number[]): ChoiceStep {
  return {
    id: sid('syl'),
    kind: 'choice',
    prompt: `Clap it out! How many parts does "${name}" have?`,
    say: `Clap the word ${name}. How many parts does it have?`,
    hint: 'Clap each beat: but-ter-fly has 3 claps.',
    explain: `${name} has ${answer} clap${answer === 1 ? '' : 's'}. Clapping words helps us hear the parts!`,
    visual: { kind: 'picture', icon, caption: name, size: 'xl' },
    options: numberChoices(answer, { count: 3, min: 1, max: 4, decoys: wrongs }),
    layout: 'row',
  }
}

export const reading: Subject = {
  id: 'reading',
  name: 'Reading',
  icon: 'book',
  tagline: 'Letters, sounds and stories',
  tone: 'sky',
  strands: ['Letter Sounds & Phonics', 'Sight Words', 'Phonemic Awareness', 'Reading Comprehension'],
  units: [
    /* ================= UNIT 1 ================= */
    {
      id: 'r-sounds',
      title: 'Letters & Sounds',
      icon: 'abc',
      tone: 'coral',
      lessons: [
        {
          id: 'r-letter-sounds',
          title: 'Letter Sounds',
          icon: 'speaker',
          blurb: 'What sound does it start with?',
          tone: 'coral',
          teach: [
            teach('Letters have sounds!', 'Every letter makes a special sound. B says buh, like at the start of bear!', 'bear'),
            teach('Sound it out', 'Say the beginning of the word out loud: sss…un! Sun starts with S!', 'sun'),
            teach('Listen closely', 'Listen to the first sound of each picture. Bear… buh! Sun… sss! Moon… mmm!', 'moon'),
          ],
          steps: [
            letterStep('b', { icon: 'bear', caption: 'bear' }, [
              { icon: 'sun', caption: 'sun' },
              { icon: 'apple', caption: 'apple' },
            ]),
            letterStep('s', { icon: 'sun', caption: 'sun' }, [
              { icon: 'cat', caption: 'cat' },
              { icon: 'fish', caption: 'fish' },
            ]),
            letterStep('m', { icon: 'moon', caption: 'moon' }, [
              { icon: 'elephant', caption: 'elephant' },
              { icon: 'banana', caption: 'banana' },
            ]),
            letterStep('f', { icon: 'frog', caption: 'frog' }, [
              { icon: 'car', caption: 'car' },
              { icon: 'cookie', caption: 'cookie' },
            ]),
            letterStep('t', { icon: 'tiger', caption: 'tiger' }, [
              { icon: 'bee', caption: 'bee' },
              { icon: 'grapes', caption: 'grapes' },
            ]),
            letterStep('d', { icon: 'dog', caption: 'dog' }, [
              { icon: 'sunflower', caption: 'flower' },
              { icon: 'rocket', caption: 'rocket' },
            ]),
            letterStep('r', { icon: 'rainbow', caption: 'rainbow' }, [
              { icon: 'penguin', caption: 'penguin' },
              { icon: 'balloon', caption: 'balloon' },
            ]),
          ],
        },
        {
          id: 'r-upper-lower',
          title: 'Big & Small Letters',
          icon: 'capitalAbc',
          blurb: 'Match ABC with abc',
          tone: 'coral',
          teach: [
            teach('Two sizes, one letter', 'Every letter has a big form and a small form. Big B and small b are the same letter!', 'capitalAbc'),
            teach('Capitals start sentences', 'We use a capital letter at the start of a sentence, and for names!', 'notebook'),
          ],
          steps: [
            matchStep(
              'Match each big letter with its little letter!',
              [
                { left: 'A', right: 'a' },
                { left: 'B', right: 'b' },
                { left: 'C', right: 'c' },
                { left: 'D', right: 'd' },
              ],
              'Big letters are called capitals. Small letters are lowercase.',
            ),
            matchStep(
              'Match the capitals with the lowercase letters!',
              [
                { left: 'M', right: 'm' },
                { left: 'S', right: 's' },
                { left: 'T', right: 't' },
                { left: 'P', right: 'p' },
              ],
              'A and a are the same letter — just different sizes!',
            ),
            {
              id: sid('lowercase'),
              kind: 'choice',
              prompt: 'Which one is the lowercase letter B?',
              say: 'Which one is the lowercase letter B?',
              hint: 'Lowercase letters are the small ones.',
              explain: 'b is the lowercase of B. The others are d, p and q — tricky twins!',
              visual: { kind: 'word', words: ['B'] },
              options: wordChoices('b', ['d', 'p', 'q']),
              layout: 'row',
            },
            {
              id: sid('capstart'),
              kind: 'choice',
              prompt: 'Which sentence starts with a capital letter?',
              say: 'Which sentence starts with a capital letter?',
              hint: 'A capital letter is a big letter.',
              explain: 'Every sentence starts with a capital letter and ends with a full stop.',
              options: wordChoices('My dog is big.', ['my dog is big.', 'my Dog is big.']),
            },
            matchStep(
              'Match each letter with a picture that starts with it!',
              [
                { left: 'B', right: 'bear' },
                { left: 'S', right: 'sun' },
                { left: 'F', right: 'fish' },
              ],
            ),
          ],
        },
        {
          id: 'r-sound-ends',
          title: 'Sounds at the Ends',
          icon: 'endsWith',
          blurb: 'Listen to the last sound',
          tone: 'coral',
          teach: [
            teach('The last sound matters', 'Words end with sounds too! Ca…t ends with t! Do…g ends with g!', 'cat'),
            teach('Say it slowly', 'Stretch the word out like taffy to hear the end: suuu…n. N!', 'sun'),
          ],
          steps: [
            endSoundStep({ icon: 'cat', caption: 'cat' }, [
              { icon: 'dog', caption: 'dog' },
              { icon: 'bus', caption: 'bus' },
            ], 't'),
            endSoundStep({ icon: 'dog', caption: 'dog' }, [
              { icon: 'cat', caption: 'cat' },
              { icon: 'bee', caption: 'bee' },
            ], 'g'),
            endSoundStep({ icon: 'sun', caption: 'sun' }, [
              { icon: 'star', caption: 'star' },
              { icon: 'pig', caption: 'pig' },
            ], 'n'),
            {
              id: sid('middle'),
              kind: 'choice',
              prompt: 'Which word has the /a/ sound in the middle?',
              say: 'Which picture has the a sound right in the middle?',
              hint: 'Say each word slowly, listening to the middle sound.',
              explain: 'Cat has /a/ in the middle: c-a-t.',
              options: pictureChoices({ icon: 'cat', caption: 'cat' }, [
                { icon: 'pig', caption: 'pig' },
                { icon: 'sun', caption: 'sun' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('howmany-sounds'),
              kind: 'choice',
              prompt: 'How many sounds are in the word "sun"?',
              say: 'How many sounds are in the word sun? sss… uuu… nnn.',
              hint: 'Stretch the word out and count each sound.',
              explain: 's-u-n has 3 sounds. Stretch a word out to count its sounds!',
              visual: { kind: 'word', words: ['s', 'u', 'n'] },
              options: numberChoices(3, { count: 3, min: 1, max: 5 }),
            },
            letterStep('p', { icon: 'penguin', caption: 'penguin' }, [
              { icon: 'fish', caption: 'fish' },
              { icon: 'bee', caption: 'bee' },
            ]),
          ],
        },
        {
          id: 'r-rhyme',
          title: 'Rhyming Words',
          icon: 'musicNote',
          blurb: 'Words that sound the same at the end',
          tone: 'coral',
          teach: [
            teach('Rhymes are word twins', 'Rhyming words end with the very same sound. Cat…hat! Star…car!', 'musicNote'),
            teach('Sing a little song', 'The frog sat on a log, next to a dog on a log! Frog, log and dog all rhyme!', 'frog'),
          ],
          steps: [
            {
              id: sid('rhyme1'),
              kind: 'choice',
              prompt: 'Which one rhymes with cat?',
              say: 'Which picture rhymes with cat? Cat… hat!',
              hint: 'Rhyming words end with the same sound.',
              explain: 'Cat and hat both end with -at. They rhyme!',
              visual: { kind: 'picture', icon: 'cat', caption: 'cat', size: 'xl' },
              options: pictureChoices({ icon: 'hat', caption: 'hat' }, [
                { icon: 'dog', caption: 'dog' },
                { icon: 'sun', caption: 'sun' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('rhyme2'),
              kind: 'choice',
              prompt: 'Which one rhymes with star?',
              say: 'Which picture rhymes with star? Star… car!',
              hint: 'Listen to the ending: -ar.',
              explain: 'Star and car both end with -ar. They rhyme!',
              visual: { kind: 'picture', icon: 'star', caption: 'star', size: 'xl' },
              options: pictureChoices({ icon: 'car', caption: 'car' }, [
                { icon: 'elephant', caption: 'elephant' },
                { icon: 'cookie', caption: 'cookie' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('rhyme3'),
              kind: 'choice',
              prompt: 'Which pair rhymes?',
              say: 'Which two words rhyme?',
              hint: 'Say both words and listen to the endings.',
              explain: 'Bee and tree both end with -ee. They rhyme!',
              options: shuffle([
                { id: sid('o'), text: 'bee · tree', correct: true },
                { id: sid('o'), text: 'dog · cat' },
                { id: sid('o'), text: 'sun · moon' },
              ]),
            },
            {
              id: sid('rhyme4'),
              kind: 'choice',
              prompt: 'Finish the rhyme: "The frog sat on a ___"',
              say: 'The frog sat on a… what? Something that rhymes with frog!',
              hint: 'Rhymes with frog: f-r-o-g … l-o-g!',
              explain: 'The frog sat on a log! Frog and log rhyme.',
              options: wordChoices('log', ['cake', 'star']),
              layout: 'row',
            },
            storyStep(
              'Which picture shows something that rhymes with "mouse"?',
              [
                { icon: 'mouse', caption: 'mouse' },
                { icon: 'question', caption: 'rhymes with?' },
              ],
              shuffle([
                { id: sid('o'), icon: 'house', caption: 'house', correct: true },
                { id: sid('o'), icon: 'elephant', caption: 'elephant' },
                { id: sid('o'), icon: 'pizza', caption: 'pizza' },
              ]),
              'Mouse and house both end with -ouse. They rhyme!',
            ),
          ],
        },
      ],
    },

    /* ================= UNIT 2 ================= */
    {
      id: 'r-words',
      title: 'Words',
      icon: 'book',
      tone: 'sky',
      lessons: [
        {
          id: 'r-sight-1',
          title: 'Sight Words 1',
          icon: 'eyes',
          blurb: 'The words we see every day',
          tone: 'sky',
          teach: [
            teach('Words we just know', 'Sight words are little words we see everywhere: the, and, you! We learn them by heart.', 'eyes'),
            teach('Spot them everywhere', 'Look around: the sun, the moon, the stars! The is everywhere once you spot it.', 'book'),
          ],
          steps: [
            sightStep('the', ['that', 'then', 'she']),
            sightStep('and', ['end', 'ant', 'an']),
            balloonStep('you', ['you', 'you', 'you', 'yes', 'yell', 'your', 'zip', 'fun'], {
              prompt: 'Pop every balloon with the word “you”!',
              say: 'Pop every balloon with the word you on it!',
              matches: 3,
              explain: 'You popped every “you” balloon — that is a sight word you know by heart!',
            }),
            sightStep('said', ['sand', 'sad', 'seed']),
            sightStep('with', ['will', 'wish', 'which']),
            {
              id: sid('sight-sent'),
              kind: 'choice',
              prompt: 'Which sentence is written correctly?',
              say: 'Which sentence uses the sight words correctly?',
              hint: 'Read the little words out loud.',
              explain: '"I see the cat and the dog." — we can read every one of those words!',
              options: wordChoices('I see the cat and the dog.', ['I see the cat adn the dog.', 'I sea the cat and dog.']),
            },
          ],
        },
        {
          id: 'r-sight-2',
          title: 'Sight Words 2',
          icon: 'search',
          blurb: 'Even more everyday words',
          tone: 'sky',
          teach: [
            teach('Tricky little words', 'Some words like to trick us: was looks like saw! Look at every letter carefully.', 'search'),
            teach('Practice makes easy', 'The more you see these words, the easier they get. Soon you will read them in your sleep!', 'moonSleep'),
          ],
          steps: [
            sightStep('was', ['saw', 'wax', 'wise']),
            sightStep('they', ['them', 'there', 'than']),
            sightStep('for', ['far', 'from', 'four']),
            balloonStep('come', ['come', 'come', 'come', 'came', 'some', 'cone', 'home', 'game'], {
              prompt: 'Pop every balloon with the word “come”!',
              say: 'Pop every balloon with the word come on it!',
              matches: 3,
              explain: 'C-O-M-E spells come — you caught them all!',
            }),
            sightStep('what', ['want', 'when', 'wet']),
            {
              id: sid('sight-fill'),
              kind: 'choice',
              prompt: 'Which word fits? "I ___ a red ball."',
              say: 'Fill in the blank. I… a red ball.',
              hint: 'Say the sentence with each word and see which one sounds right.',
              explain: '"I have a red ball" makes sense. Have is our sight word!',
              options: wordChoices('have', ['was', 'they']),
              layout: 'row',
            },
          ],
        },
        {
          id: 'r-word-families',
          title: 'Word Families',
          icon: 'family',
          blurb: 'Words that share an ending',
          tone: 'sky',
          teach: [
            teach('Word families', 'Words in a family share their ending. Cat, hat and bat all end with at. They are the at family!', 'family'),
            teach('Swap the first letter', 'Change the first letter and make a brand new word! Cat becomes hat, bat, and rat!', 'cat'),
          ],
          steps: [
            {
              id: sid('fam1'),
              kind: 'choice',
              prompt: 'Which word belongs to the -at family?',
              say: 'Which word belongs to the at family?',
              hint: 'Every word in a family ends with the same letters.',
              explain: 'Bat, cat, hat and mat all end with -at. Fresh from the -at family!',
              visual: { kind: 'word', words: ['-at'], caption: 'the -at family' },
              options: wordChoices('bat', ['bug', 'pie', 'sun']),
              layout: 'row',
            },
            {
              id: sid('fam2'),
              kind: 'choice',
              prompt: 'Which word belongs to the -ig family?',
              say: 'Which word belongs to the ig family?',
              hint: 'Listen for the -ig ending.',
              explain: 'Pig, wig, dig, big — all end with -ig.',
              visual: { kind: 'word', words: ['-ig'] },
              options: wordChoices('wig', ['wag', 'wave', 'wink']),
              layout: 'row',
            },
            {
              id: sid('fam3'),
              kind: 'choice',
              prompt: 'Change the first letter of "cat" to make a new word!',
              say: 'Change the first letter of cat. Which one is a real word?',
              hint: 'Say each new word out loud — does it sound real?',
              explain: 'Change c to h and you get hat. Changing one letter makes a whole new word!',
              visual: { kind: 'word', words: ['c', 'at'] },
              options: wordChoices('hat', ['zat', 'gat', 'vat']),
              layout: 'row',
            },
            buildWordStep('cat', { kind: 'picture', icon: 'cat', caption: 'cat', size: 'lg' }, 'Spell the word for this picture!'),
            buildWordStep('sun', { kind: 'picture', icon: 'sun', caption: 'sun', size: 'lg' }),
            wordStep('Which word do you see?', ['dog'], wordChoices('dog', ['bog', 'dig', 'dot']), 'Dog, bog, dig and dot all look alike — look closely!'),
            /* drive to the word that rhymes with cat: bat, hat, rat */
            raceStep('rhymes with “cat”', 'hat', ['dog', 'sun'], {
              say: 'Drive to the word that rhymes with cat!',
              explain: 'Cat and hat both end with -at. They rhyme!',
            }),
          ],
        },
        {
          id: 'r-syllables',
          title: 'Clap the Syllables',
          icon: 'clap',
          blurb: 'Count the beats in a word',
          tone: 'sky',
          teach: [
            teach('Words have beats', 'Words have claps inside them, called syllables. But-ter-fly has three claps!', 'clap'),
            teach('Clap along with me', 'Clap with me: pup…py! Two claps! El…e…phant! Three claps!', 'elephant'),
          ],
          steps: [
            syllableStep('cat', 'cat', 1, [2, 3]),
            syllableStep('dog', 'puppy', 2, [1, 3]),
            syllableStep('butterfly', 'butterfly', 3, [1, 2]),
            syllableStep('elephant', 'elephant', 3, [1, 2]),
            syllableStep('sun', 'sun', 1, [2, 4]),
            syllableStep('banana', 'banana', 3, [1, 2]),
            {
              id: sid('syl-sort'),
              kind: 'choice',
              prompt: 'Which word has 2 claps?',
              say: 'Which word has two claps?',
              hint: 'Clap each word as you say it.',
              explain: 'Rab-bit has 2 claps. Clapping breaks words into parts!',
              options: wordChoices('rabbit', ['cat', 'elephant']),
              layout: 'row',
            },
          ],
        },
      ],
    },

    /* ================= UNIT 3 ================= */
    {
      id: 'r-stories',
      title: 'Reading Stories',
      icon: 'book',
      tone: 'grape',
      lessons: [
        {
          id: 'r-sentences',
          title: 'Read the Sentence',
          icon: 'notebook',
          blurb: 'Match sentences to pictures',
          tone: 'grape',
          teach: [
            teach('Words paint pictures', 'A sentence can paint a picture in your mind. The cat sat on the mat. Can you see it?', 'cat'),
            teach('Read, then look', 'Read the words first, then find the picture that matches. You can do it!', 'notebook'),
          ],
          steps: [
            storyStep(
              'Read the sentence, then tap the right picture.',
              [{ icon: 'cat', caption: 'The cat sat.' }, { icon: 'chair', caption: 'on the mat.' }],
              shuffle([
                { id: sid('o'), icon: 'cat', caption: 'cat on a mat', correct: true },
                { id: sid('o'), icon: 'dog', caption: 'dog on a bed' },
                { id: sid('o'), icon: 'bird', caption: 'bird in a tree' },
              ]),
              'The sentence says the cat sat on the mat.',
            ),
            {
              id: sid('sent2'),
              kind: 'choice',
              prompt: 'The big red hen is in the pen. Where is the hen?',
              say: 'The big red hen is in the pen. Where is the hen?',
              hint: 'Listen for the place word: in the pen.',
              explain: 'The hen is in the pen.',
              options: wordChoices('in the pen', ['in the den', 'on the bed']),
            },
            {
              id: sid('sent3'),
              kind: 'choice',
              prompt: 'Sam has three dogs. How many dogs does Sam have?',
              say: 'Sam has three dogs. How many dogs does Sam have?',
              hint: 'Look for the number word.',
              explain: 'Three! The number word in the sentence tells you how many.',
              options: numberChoices(3, { count: 3, min: 1, max: 6 }),
            },
            {
              id: sid('sent4'),
              kind: 'choice',
              prompt: 'Which sentence tells you where something is?',
              say: 'Which sentence tells you where something is?',
              hint: 'Position words are in, on, under, above, next to.',
              explain: '"The cup is on the table" tells us where the cup is.',
              options: wordChoices('The cup is on the table.', ['The cup is blue.', 'She has a cup.']),
            },
            storyStep(
              'Read: "A little frog hops onto a log." Tap the picture that matches.',
              [
                { icon: 'frog', caption: 'frog' },
                { icon: 'log', caption: 'log' },
              ],
              shuffle([
                { id: sid('o'), icon: 'frog', caption: 'frog on a log', correct: true },
                { id: sid('o'), icon: 'frog', caption: 'frog in water' },
                { id: sid('o'), icon: 'log', caption: 'just a log' },
              ]),
              'The frog hops onto the log — both are in the picture.',
            ),
          ],
        },
        {
          id: 'r-story-order',
          title: 'Story Order',
          icon: 'one',
          blurb: 'Beginning, middle and end',
          tone: 'grape',
          teach: [
            teach('Stories have order', 'Every story has a beginning, a middle, and an end. First the seed, then the sprout, then the flower!', 'seed'),
            teach('First, next, last', 'Words like first, next and last tell you the order of a story. First we wake up, next we eat, last we play!', 'sunrise'),
          ],
          steps: [
            orderStep(
              'Tap the pictures in the right order: what happens first?',
              [
                { icon: 'seed', label: 'seed', order: 1 },
                { icon: 'sprout', label: 'sprout', order: 2 },
                { icon: 'leaves', label: 'plant', order: 3 },
                { icon: 'sunflower', label: 'flower', order: 4 },
              ],
              'A seed grows into a sprout, then a plant, and finally a flower.',
            ),
            orderStep(
              'Put the butterfly story in order!',
              [
                { icon: 'egg', label: 'egg', order: 1 },
                { icon: 'caterpillar', label: 'caterpillar', order: 2 },
                { icon: 'cocoon', label: 'chrysalis', order: 3 },
                { icon: 'butterfly', label: 'butterfly', order: 4 },
              ],
              'Egg, caterpillar, chrysalis, butterfly — that is the life cycle.',
            ),
            orderStep(
              'What does the boy do first?',
              [
                { icon: 'bed', label: 'wake up', order: 1 },
                { icon: 'bowl', label: 'eat breakfast', order: 2 },
                { icon: 'backpack', label: 'pack a bag', order: 3 },
                { icon: 'bus', label: 'ride the bus', order: 4 },
              ],
              'First you wake up, then eat, pack, and ride. That is the order of a morning!',
            ),
            storyStep(
              'Which picture shows the END of the story?',
              [
                { icon: 'egg', caption: 'first' },
                { icon: 'chick', caption: 'next' },
                { icon: 'hen', caption: 'last' },
              ],
              shuffle([
                { id: sid('o'), icon: 'hen', caption: 'the grown hen', correct: true },
                { id: sid('o'), icon: 'egg', caption: 'the egg' },
                { id: sid('o'), icon: 'chick', caption: 'the chick' },
              ]),
              'The egg hatches into a chick, and the chick grows into a hen.',
            ),
          ],
        },
        {
          id: 'r-spell',
          title: 'Spell It!',
          icon: 'abc',
          blurb: 'Build words from letters',
          tone: 'grape',
          teach: [
            teach('Words are letter chains', 'Words are made of letters in a special order. D…o…g spells dog!', 'dog'),
            teach('Sound and build', 'Say the word slowly and catch each sound. Then pick the letter for each one!', 'abc'),
          ],
          steps: [
            buildWordStep('dog', { kind: 'picture', icon: 'dog', caption: 'dog', size: 'lg' }),
            buildWordStep('cat', { kind: 'picture', icon: 'cat', caption: 'cat', size: 'lg' }),
            buildWordStep('sun', { kind: 'picture', icon: 'sun', caption: 'sun', size: 'lg' }),
            buildWordStep('fish', { kind: 'picture', icon: 'fish', caption: 'fish', size: 'lg' }),
            buildWordStep('frog', { kind: 'picture', icon: 'frog', caption: 'frog', size: 'lg' }),
            buildWordStep('star', { kind: 'picture', icon: 'star', caption: 'star', size: 'lg' }),
            {
              id: sid('spell-last'),
              kind: 'choice',
              prompt: 'Which spelling is correct?',
              say: 'Which spelling of the word book is correct?',
              hint: 'Sound it out: b-oo-k.',
              explain: 'b-oo-k — two o letters make the long oo sound.',
              options: wordChoices('book', ['buk', 'booc']),
              layout: 'row',
            },
          ],
        },

        {
          id: 'r-compound',
          title: 'Compound Words',
          icon: 'puzzle',
          blurb: 'Two little words make one big word',
          tone: 'grape',
          teach: [
            teach('Two words snap together!', 'Two little words can snap together to make one big word. Sun plus flower makes sunflower!', 'sunflower'),
            teach('Picture the two parts', 'A rainbow is a bow of colours in the sky after rain. Rain plus bow!', 'rainbow'),
          ],
          steps: [
            {
              id: sid('cp1'),
              kind: 'choice',
              prompt: 'Which two pictures make a new word together?',
              say: 'Sun and flower snap together to make which big word?',
              hint: 'Say each picture name, then try saying both together.',
              explain: 'Sun plus flower makes sunflower — a compound word!',
              options: shuffle([
                { id: sid('o'), text: 'sunflower', correct: true },
                { id: sid('o'), text: 'sunball' },
                { id: sid('o'), text: 'flowerpot' },
              ]),
              visual: {
                kind: 'story',
                frames: [
                  { icon: 'sun', caption: 'sun' },
                  { icon: 'plusBadge', caption: 'plus' },
                  { icon: 'sunflower', caption: 'flower' },
                ],
              },
              layout: 'row',
            },
            {
              id: sid('cp2'),
              kind: 'choice',
              prompt: 'Butterfly is a compound word. Which pictures are its two parts?',
              say: 'Butterfly has two little words inside. Which pictures show them?',
              hint: 'Butter… fly! Say both parts out loud.',
              explain: 'Butter plus fly makes butterfly!',
              options: pictureChoices({ icon: 'butterfly', caption: 'butterfly' }, [
                { icon: 'bee', caption: 'bee' },
                { icon: 'worm', caption: 'worm' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('cp3'),
              kind: 'choice',
              prompt: 'Which one is a real compound word?',
              say: 'Which one is a real word made from two little words?',
              hint: 'Say each choice out loud — does it sound like a real thing?',
              explain: 'Rainbow is real: rain plus bow! The others are made-up words.',
              options: wordChoices('rainbow', ['cloudhat', 'starshoe']),
              layout: 'row',
            },
            {
              id: sid('cp4'),
              kind: 'choice',
              prompt: 'Snowman is made of which two words?',
              say: 'Snowman is a compound word. Which two words made it?',
              hint: 'What is a snowman made of? And what is on top?',
              explain: 'Snow plus man makes snowman!',
              options: wordChoices('snow + man', ['star + man', 'sand + man']),
              layout: 'row',
            },
          ],
        },

        {
          id: 'r-question-words',
          title: 'Question Words',
          icon: 'question',
          blurb: 'Who, what, where, when, why',
          tone: 'grape',
          teach: [
            teach('Questions start with special words', 'Who, what, where, when and why are question words. They ask for different things!', 'question'),
            teach('Who asks about people', 'Who asks about a person or animal. Who is your best friend?', 'family'),
            teach('Where asks about place', 'Where asks about a place. Where do fish live? In the water!', 'fish'),
          ],
          steps: [
            {
              id: sid('qw1'),
              kind: 'choice',
              prompt: 'Which word asks about a place?',
              say: 'Which word asks about a place?',
              hint: 'Think about the words: who, what, where.',
              explain: 'Where asks about a place — like where do you live?',
              options: wordChoices('where', ['who', 'what']),
              layout: 'row',
            },
            {
              id: sid('qw2'),
              kind: 'choice',
              prompt: '…do bears eat? Which question word fits?',
              say: 'Blank do bears eat? Which question word fits?',
              hint: 'The answer is a thing — honey! What asks about things.',
              explain: 'What do bears eat? What asks about a thing.',
              visual: { kind: 'word', words: ['?', 'do bears eat?'] },
              options: wordChoices('What', ['Who', 'When']),
              layout: 'row',
            },
            {
              id: sid('qw3'),
              kind: 'choice',
              prompt: 'Which question matches: In the morning!',
              say: 'Which question has the answer in the morning?',
              hint: 'In the morning is a time, not a place or a person.',
              explain: 'When do you wake up? In the morning! When asks about time.',
              options: wordChoices('When do you wake up?', ['Where do you wake up?', 'Who do you wake up?']),
              layout: 'row',
            },
            {
              id: sid('qw4'),
              kind: 'choice',
              prompt: 'Which word asks about a person?',
              say: 'Which word asks about a person or animal?',
              hint: 'Who is all about people and friends.',
              explain: 'Who asks about a person — like who is your teacher?',
              options: wordChoices('who', ['why', 'when']),
              layout: 'row',
            },
          ],
        },

        {
          id: 'r-vowels',
          title: 'Vowel Power',
          icon: 'abc',
          blurb: 'A, E, I, O, U and sometimes Y',
          tone: 'grape',
          teach: [
            teach('The five vowel heroes', 'A, E, I, O and U are vowels. Every word needs at least one vowel to hold it together!', 'abc'),
            teach('Short vowel sounds', 'A says ah like apple. E says eh like elephant. I says ih like igloo!', 'apple'),
            teach('Vowels glue words together', 'Try reading c-t without a vowel… ck-t! Add an a: cat! Vowels are powerful.', 'cat'),
          ],
          steps: [
            {
              id: sid('vw1'),
              kind: 'choice',
              prompt: 'Which letter is a vowel?',
              say: 'Which one of these letters is a vowel?',
              hint: 'The vowels are A, E, I, O, U.',
              explain: 'E is a vowel! B and T are consonants.',
              options: wordChoices('E', ['B', 'T']),
              layout: 'row',
            },
            {
              id: sid('vw2'),
              kind: 'choice',
              prompt: 'Which vowel is in the middle of cat?',
              say: 'Say the word cat. Which vowel sits in the middle?',
              hint: 'C…a…t! Listen to the middle sound.',
              explain: 'The letter A is in the middle of cat!',
              visual: { kind: 'word', words: ['c', '?', 't'] },
              options: wordChoices('a', ['e', 'o']),
              layout: 'row',
            },
            {
              id: sid('vw3'),
              kind: 'choice',
              prompt: 'Which word has the vowel I?',
              say: 'Which word has the vowel I in it?',
              hint: 'Say each word slowly and listen for ih.',
              explain: 'Fish has the vowel I: f-i-sh!',
              options: wordChoices('fish', ['dog', 'hen']),
              layout: 'row',
            },
            {
              id: sid('vw4'),
              kind: 'choice',
              prompt: 'How many vowels does our alphabet have?',
              say: 'How many vowels are in our alphabet?',
              hint: 'Count them: A, E, I, O, U.',
              explain: 'Five vowels: A, E, I, O and U!',
              options: [
                { id: sid('o'), text: '5', correct: true },
                { id: sid('o'), text: '3' },
                { id: sid('o'), text: '7' },
              ],
              layout: 'row',
            },
          ],
        },

        {
          id: 'r-naming',
          title: 'Naming Words',
          icon: 'pencil',
          blurb: 'People, places and things',
          tone: 'grape',
          teach: [
            teach('Naming words', 'A naming word tells you WHAT something is: dog, park, ball, grandma. They name people, places and things!', 'pencil'),
            teach('People and places', 'Teacher and doctor name people. School and park name places!', 'school'),
            teach('Things everywhere', 'Ball, book, pizza — naming words are all around you. Look around and name things!', 'ball'),
          ],
          steps: [
            {
              id: sid('nm1'),
              kind: 'choice',
              prompt: 'Which one is a naming word for a person?',
              say: 'Which word names a person?',
              hint: 'Think about who you know.',
              explain: 'Teacher names a person! Ball and tree are things.',
              options: wordChoices('teacher', ['ball', 'tree']),
              layout: 'row',
            },
            {
              id: sid('nm2'),
              kind: 'choice',
              prompt: 'Which one names a place?',
              say: 'Which word names a place?',
              hint: 'A place is somewhere you can go.',
              explain: 'Park names a place — somewhere you can go and play!',
              options: wordChoices('park', ['cookie', 'puppy']),
              layout: 'row',
            },
            {
              id: sid('nm3'),
              kind: 'choice',
              prompt: 'Find the naming word: The dog runs fast.',
              say: 'Listen: the dog runs fast. Which word names a thing?',
              hint: 'Which word is a living thing you can pet?',
              explain: 'Dog is the naming word — it names an animal!',
              options: wordChoices('dog', ['runs', 'the']),
              layout: 'row',
            },
            {
              id: sid('nm4'),
              kind: 'choice',
              prompt: 'Which picture shows a naming word?',
              say: 'Which one is a naming word for a thing you can eat?',
              hint: 'Yum yum — you eat it!',
              explain: 'An apple is a thing you can eat — a perfect naming word!',
              options: pictureChoices({ icon: 'apple', caption: 'apple' }, [
                { icon: 'hand', caption: 'clapping' },
                { icon: 'moonSleep', caption: 'sleeping' },
              ]),
              layout: 'grid-3',
            },
          ],
        },
      ],
    },
  ],
}
