import type { Subject } from '../types'
import {
  matchStep,
  numberChoices,
  orderStep,
  pictureChoices,
  shuffle,
  sid,
  sortStep,
  teach,
  wordChoices,
} from './builders'

export const science: Subject = {
  id: 'science',
  name: 'Science',
  icon: 'microscope',
  tagline: 'Animals, plants and our world',
  tone: 'grass',
  strands: ['Living Things', 'Plants & Animals', 'Earth & Sky', 'Sorting & Observing'],
  units: [
    /* ================= UNIT 1 ================= */
    {
      id: 's-living',
      title: 'Living Things',
      icon: 'sprout',
      tone: 'grass',
      lessons: [
        {
          id: 's-living-or-not',
          title: 'Living or Not Living',
          icon: 'tree',
          blurb: 'Is it alive?',
          tone: 'grass',
          teach: [
            teach('Living things are alive!', 'Living things grow, breathe, eat and move. You are living — so is a dog, a tree and a bee!', 'sprout'),
            teach('Not everything is alive', 'Rocks, chairs and cars do not grow or eat. They are not living things.', 'rock'),
            teach('What do living things need?', 'Every living thing needs water, food and air to stay alive!', 'waterDrop'),
          ],
          steps: [
            sortStep(
              'Living things grow and need food. Sort them!',
              [
                { id: 'alive', label: 'Living', icon: 'sprout', tone: 'grass' },
                { id: 'not', label: 'Not living', icon: 'rock', tone: 'grape' },
              ],
              [
                { icon: 'dog', label: 'dog', bin: 'alive' },
                { icon: 'rock', label: 'rock', bin: 'not' },
                { icon: 'tree', label: 'tree', bin: 'alive' },
                { icon: 'car', label: 'car', bin: 'not' },
                { icon: 'bee', label: 'bee', bin: 'alive' },
                { icon: 'chair', label: 'chair', bin: 'not' },
              ],
              'Living things grow, breathe and need food. Rocks and chairs do not!',
            ),
            {
              id: sid('alive1'),
              kind: 'choice',
              prompt: 'Which one is a living thing?',
              say: 'Which one is a living thing?',
              hint: 'Living things grow and need water and food.',
              explain: 'A sunflower grows from a seed and needs water and sunlight — it is alive!',
              options: pictureChoices({ icon: 'sunflower', caption: 'sunflower' }, [
                { icon: 'book', caption: 'book' },
                { icon: 'cloud', caption: 'cloud' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('alive2'),
              kind: 'choice',
              prompt: 'Which one is NOT living?',
              say: 'Which one is not living?',
              hint: 'Not-living things do not eat or grow.',
              explain: 'A bicycle does not eat, breathe or grow. It has never been alive.',
              options: pictureChoices({ icon: 'bicycle', caption: 'bicycle' }, [
                { icon: 'turtle', caption: 'turtle' },
                { icon: 'leaves', caption: 'plant' },
              ]),
              layout: 'grid-3',
            },
            orderStep(
              'Living things change as they grow. Put them in order!',
              [
                { icon: 'seed', label: 'seed', order: 1 },
                { icon: 'sprout', label: 'sprout', order: 2 },
                { icon: 'leaves', label: 'young plant', order: 3 },
                { icon: 'tree', label: 'big tree', order: 4 },
              ],
              'Living things grow and change over time. A seed becomes a tree!',
            ),
            {
              id: sid('alive3'),
              kind: 'choice',
              prompt: 'What do living things need to stay alive?',
              say: 'What do living things need to stay alive?',
              hint: 'Think about what you need every single day.',
              explain: 'Water, food and air! Every living thing needs them.',
              options: pictureChoices({ icon: 'waterDrop', caption: 'water, food and air' }, [
                { icon: 'tv', caption: 'television' },
                { icon: 'candy', caption: 'only candy' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('alive4'),
              kind: 'choice',
              prompt: 'Which one is alive AND can move on its own?',
              say: 'Which one is alive and can move all by itself?',
              hint: 'Plants are alive, but they cannot walk!',
              explain: 'A duck is alive and moves by itself. A tree is alive but stays in place.',
              options: pictureChoices({ icon: 'duck', caption: 'duck' }, [
                { icon: 'tree', caption: 'tree' },
                { icon: 'rock', caption: 'rock' },
              ]),
              layout: 'grid-3',
            },
          ],
        },
        {
          id: 's-animal-food',
          title: 'What Animals Eat',
          icon: 'carrot',
          blurb: 'Match animals to their food',
          tone: 'grass',
          teach: [
            teach('Every animal eats', 'Animals need food to run, jump and grow. But different animals like different foods!', 'carrot'),
            teach('Panda snacks', 'Pandas munch bamboo all day long. Crunch, crunch!', 'bamboo'),
            teach('Monkey snacks', 'Monkeys swing through trees eating sweet bananas!', 'banana'),
          ],
          steps: [
            matchStep(
              'Match each animal with the food it eats!',
              [
                { left: 'rabbit', right: 'carrot' },
                { left: 'monkey', right: 'banana' },
                { left: 'panda', right: 'bamboo' },
                { left: 'dog', right: 'bone' },
              ],
              'Rabbits crunch carrots, monkeys love bananas, pandas eat bamboo and dogs chew bones.',
            ),
            matchStep(
              'Match the animals with their favourite snack!',
              [
                { left: 'bear', right: 'honey' },
                { left: 'bird', right: 'worm' },
                { left: 'mouse', right: 'cheese' },
                { left: 'bee', right: 'blossom' },
              ],
              'Bears love honey, birds peck worms, mice nibble cheese and bees sip flowers.',
            ),
            {
              id: sid('food1'),
              kind: 'choice',
              prompt: 'Which animal eats only plants?',
              say: 'Which animal eats only plants?',
              hint: 'Grass-eating animals have flat teeth for grinding.',
              explain: 'Cows eat grass and plants. Animals that eat only plants are herbivores.',
              options: pictureChoices({ icon: 'cow', caption: 'cow' }, [
                { icon: 'lion', caption: 'lion' },
                { icon: 'shark', caption: 'shark' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('food2'),
              kind: 'choice',
              prompt: 'What does a baby need to grow?',
              say: 'What does a baby need to grow big and strong?',
              hint: 'Babies drink something from their mums.',
              explain: 'Milk! Baby animals drink milk from their mothers.',
              options: pictureChoices({ icon: 'milk', caption: 'milk' }, [
                { icon: 'soda', caption: 'soda' },
                { icon: 'lollipop', caption: 'lollipops' },
              ]),
              layout: 'grid-3',
            },
            sortStep(
              'Sort the animals: which ones live in water?',
              [
                { id: 'water', label: 'In water', icon: 'wave', tone: 'sky' },
                { id: 'land', label: 'On land', icon: 'hills', tone: 'grass' },
              ],
              [
                { icon: 'fish', label: 'fish', bin: 'water' },
                { icon: 'elephant', label: 'elephant', bin: 'land' },
                { icon: 'octopus', label: 'octopus', bin: 'water' },
                { icon: 'lion', label: 'lion', bin: 'land' },
                { icon: 'dolphin', label: 'dolphin', bin: 'water' },
                { icon: 'monkey', label: 'monkey', bin: 'land' },
              ],
              'Fish, dolphins and octopuses live in water. Elephants, lions and monkeys live on land.',
            ),
          ],
        },
        {
          id: 's-animal-homes',
          title: 'Where Animals Live',
          icon: 'house',
          blurb: 'Match animals to their homes',
          tone: 'grass',
          teach: [
            teach('Animals have homes too', 'Animals have special homes that keep them safe and dry. A bird sleeps in a nest!', 'nest'),
            teach('Home under the sea', 'Fish live in water — oceans, rivers and ponds. Their whole world is wet!', 'fish'),
            teach('Home underground', 'Rabbits dig long tunnels called burrows. Mice make cosy nests underground!', 'rabbit'),
          ],
          steps: [
            matchStep(
              'Match each animal with its home!',
              [
                { left: 'bird', right: 'nest' },
                { left: 'squirrel', right: 'tree' },
                { left: 'fish', right: 'wave' },
              ],
              'Birds build nests, squirrels live in trees and fish swim in water.',
            ),
            {
              id: sid('home1'),
              kind: 'choice',
              prompt: 'Where does a bee live?',
              say: 'Where does a bee live?',
              hint: 'Bees make something sweet in their home.',
              explain: 'Bees live in a hive and make honey there.',
              options: pictureChoices({ icon: 'bee', caption: 'in a hive' }, [
                { icon: 'hole', caption: 'in a hole underground' },
                { icon: 'nest', caption: 'in a nest' },
              ]),
              layout: 'grid-3',
            },
            sortStep(
              'Sort where these animals make their homes!',
              [
                { id: 'tree', label: 'In trees', icon: 'tree', tone: 'grass' },
                { id: 'ground', label: 'Underground', icon: 'hole', tone: 'coral' },
              ],
              [
                { icon: 'bird', label: 'bird', bin: 'tree' },
                { icon: 'ant', label: 'ant', bin: 'ground' },
                { icon: 'squirrel', label: 'squirrel', bin: 'tree' },
                { icon: 'worm', label: 'worm', bin: 'ground' },
                { icon: 'owl', label: 'owl', bin: 'tree' },
                { icon: 'rabbit', label: 'rabbit', bin: 'ground' },
              ],
              'Birds, squirrels and owls nest in trees. Ants, worms and rabbits dig underground.',
            ),
            {
              id: sid('home2'),
              kind: 'choice',
              prompt: 'Which animal carries its home on its back?',
              say: 'Which animal carries its home on its back?',
              hint: 'It has a hard shell and moves very slowly.',
              explain: 'A turtle carries its shell everywhere it goes!',
              options: pictureChoices({ icon: 'turtle', caption: 'turtle' }, [
                { icon: 'rabbit', caption: 'rabbit' },
                { icon: 'eagle', caption: 'eagle' },
              ]),
              layout: 'grid-3',
            },
          ],
        },
      ],
    },

    /* ================= UNIT 2 ================= */
    {
      id: 's-world',
      title: 'Our World',
      icon: 'earth',
      tone: 'sky',
      lessons: [
        {
          id: 's-weather',
          title: 'Weather & Seasons',
          icon: 'weather',
          blurb: 'Spring, summer, fall and winter',
          tone: 'sky',
          teach: [
            teach('Weather changes every day', 'Weather is what the sky is doing: sunny, rainy, snowy or windy. It can change fast!', 'weather'),
            teach('Rain falls from clouds', 'Grey clouds are full of water drops. When they get too heavy — drip, drop, rain!', 'cloudRain'),
            teach('Four seasons a year', 'The year has four seasons: spring, summer, fall and winter. Each one feels different!', 'sunflower'),
          ],
          steps: [
            sortStep(
              'Sort these into the right season!',
              [
                { id: 'summer', label: 'Summer', icon: 'sun', tone: 'sun' },
                { id: 'winter', label: 'Winter', icon: 'snowflake', tone: 'sky' },
              ],
              [
                { icon: 'beach', label: 'beach day', bin: 'summer' },
                { icon: 'snowman', label: 'snowman', bin: 'winter' },
                { icon: 'iceCream', label: 'ice cream', bin: 'summer' },
                { icon: 'mitten', label: 'mittens', bin: 'winter' },
                { icon: 'sunglasses', label: 'sunglasses', bin: 'summer' },
                { icon: 'scarf', label: 'scarf', bin: 'winter' },
              ],
              'Summer is hot — we swim and eat ice cream. Winter is cold — we wear mittens and scarves!',
            ),
            sortStep(
              'Sort these into spring or fall!',
              [
                { id: 'spring', label: 'Spring', icon: 'blossom', tone: 'berry' },
                { id: 'fall', label: 'Fall', icon: 'mapleLeaf', tone: 'coral' },
              ],
              [
                { icon: 'tulip', label: 'tulips', bin: 'spring' },
                { icon: 'mapleLeaf', label: 'falling leaves', bin: 'fall' },
                { icon: 'chick', label: 'baby chicks', bin: 'spring' },
                { icon: 'pumpkin', label: 'pumpkin', bin: 'fall' },
                { icon: 'cloudRain', label: 'spring rain', bin: 'spring' },
                { icon: 'apple', label: 'apple picking', bin: 'fall' },
              ],
              'In spring flowers bloom and babies are born. In fall leaves change colour and we pick apples.',
            ),
            {
              id: sid('weather1'),
              kind: 'choice',
              prompt: 'What should you wear when it rains?',
              say: 'What should you wear when it rains?',
              hint: 'Rain is wet!',
              explain: 'A raincoat and boots keep you dry in the rain.',
              options: pictureChoices({ icon: 'coat', caption: 'raincoat' }, [
                { icon: 'shorts', caption: 'shorts' },
                { icon: 'swimsuit', caption: 'swimsuit' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('weather2'),
              kind: 'choice',
              prompt: 'What is the weather like when you need an umbrella?',
              say: 'What is the weather like when you need an umbrella?',
              hint: 'Umbrellas keep something off your head.',
              explain: 'Rainy! We use umbrellas when it is raining.',
              options: pictureChoices({ icon: 'cloudRain', caption: 'rainy' }, [
                { icon: 'sun', caption: 'sunny' },
                { icon: 'cloudSnow', caption: 'snowy' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('weather3'),
              kind: 'choice',
              prompt: 'How many seasons are there?',
              say: 'How many seasons are there in a year?',
              hint: 'Spring, summer… keep counting!',
              explain: 'Four seasons: spring, summer, fall and winter.',
              visual: { kind: 'word', words: ['blossom', 'sun', 'mapleLeaf', 'snowflake'] },
              options: numberChoices(4, { count: 3, min: 2, max: 7 }),
            },
          ],
        },
        {
          id: 's-day-night',
          title: 'Day & Night',
          icon: 'moon',
          blurb: 'The sun and the moon',
          tone: 'sky',
          teach: [
            teach('The sun lights the day', 'The sun is a giant star that lights up our day. It rises in the morning and sets in the evening!', 'sunHappy'),
            teach('The moon lights the night', 'At night we see the moon and twinkling stars. The moon reflects the light of the sun!', 'moonSleep'),
            teach('The world turns', 'Day and night happen because the Earth slowly spins, like a top! One spin is one whole day.', 'earth'),
          ],
          steps: [
            sortStep(
              'Sort these into day and night!',
              [
                { id: 'day', label: 'Day', icon: 'sun', tone: 'sun' },
                { id: 'night', label: 'Night', icon: 'moon', tone: 'grape' },
              ],
              [
                { icon: 'sunHappy', label: 'sunshine', bin: 'day' },
                { icon: 'star', label: 'stars', bin: 'night' },
                { icon: 'rooster', label: 'rooster crowing', bin: 'day' },
                { icon: 'owl', label: 'owl awake', bin: 'night' },
                { icon: 'rainbow', label: 'rainbow', bin: 'day' },
                { icon: 'moonSleep', label: 'moon', bin: 'night' },
              ],
              'The sun shines in the day. At night we see the moon and stars.',
            ),
            orderStep(
              'Put a whole day in order!',
              [
                { icon: 'sunrise', label: 'sunrise', order: 1 },
                { icon: 'sun', label: 'midday', order: 2 },
                { icon: 'sunset', label: 'sunset', order: 3 },
                { icon: 'moon', label: 'night', order: 4 },
              ],
              'The sun rises in the morning, is highest at midday, sets in the evening, and then night comes.',
            ),
            {
              id: sid('sun1'),
              kind: 'choice',
              prompt: 'What gives us light during the day?',
              say: 'What gives us light during the day?',
              hint: 'It is big, yellow and up in the sky.',
              explain: 'The sun! It is a giant star that gives us light and warmth.',
              options: pictureChoices({ icon: 'sunHappy', caption: 'the sun' }, [
                { icon: 'flashlight', caption: 'a flashlight' },
                { icon: 'candle', caption: 'a candle' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('sun2'),
              kind: 'choice',
              prompt: 'Which one is hottest?',
              say: 'Which one is the hottest?',
              hint: 'It is made of fire.',
              explain: 'The sun is extremely hot — much hotter than fire or a light bulb!',
              options: pictureChoices({ icon: 'sunHappy', caption: 'the sun' }, [
                { icon: 'fire', caption: 'a campfire' },
                { icon: 'bulb', caption: 'a light bulb' },
              ]),
              layout: 'grid-3',
            },
          ],
        },
        {
          id: 's-plants',
          title: 'Plants',
          icon: 'sunflower',
          blurb: 'How plants grow',
          tone: 'sky',
          teach: [
            teach('A seed becomes a plant', 'Inside every seed sleeps a tiny plant. Give it water and sunshine and it wakes up!', 'seed'),
            teach('Roots drink, leaves eat', 'Roots drink water from the soil. Leaves catch sunlight to make food. Teamwork!', 'sprout'),
            teach('Plants grow slowly', 'Plants grow a little bit every day. Soon a seed becomes a big sunflower!', 'sunflower'),
          ],
          steps: [
            {
              id: sid('plant1'),
              kind: 'choice',
              prompt: 'What does a plant need to grow?',
              say: 'What does a plant need to grow?',
              hint: 'A plant drinks from its roots and eats sunshine.',
              explain: 'Plants need water, sunlight and soil to grow big and strong.',
              options: pictureChoices({ icon: 'waterDrop', caption: 'water and sunlight' }, [
                { icon: 'pizza', caption: 'pizza' },
                { icon: 'phone', caption: 'a phone' },
              ]),
              layout: 'grid-3',
            },
            orderStep(
              'Put the plant in order as it grows!',
              [
                { icon: 'seed', label: 'seed', order: 1 },
                { icon: 'sprout', label: 'sprout', order: 2 },
                { icon: 'leaves', label: 'leaves grow', order: 3 },
                { icon: 'sunflower', label: 'flower blooms', order: 4 },
              ],
              'A seed soaks up water, sprouts, grows leaves and finally blooms into a flower.',
            ),
            {
              id: sid('plant2'),
              kind: 'choice',
              prompt: 'Which part of the plant drinks water from the ground?',
              say: 'Which part of the plant drinks water from the ground?',
              hint: 'It grows under the soil and holds the plant still.',
              explain: 'Roots! They grow underground and soak up water for the plant.',
              options: pictureChoices({ icon: 'sprout', caption: 'the roots' }, [
                { icon: 'blossom', caption: 'the flower' },
                { icon: 'leafSingle', caption: 'the leaf' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('plant3'),
              kind: 'choice',
              prompt: 'Which part makes food from sunlight?',
              say: 'Which part of the plant makes food using sunlight?',
              hint: 'It is green and flat.',
              explain: 'Leaves use sunlight to make food for the plant. That is called photosynthesis!',
              options: pictureChoices({ icon: 'leafSingle', caption: 'the leaves' }, [
                { icon: 'log', caption: 'the stem' },
                { icon: 'seed', caption: 'the seed' },
              ]),
              layout: 'grid-3',
            },
            sortStep(
              'Sort: which things are plants?',
              [
                { id: 'plant', label: 'Plants', icon: 'sprout', tone: 'grass' },
                { id: 'animal', label: 'Animals', icon: 'pawPrints', tone: 'coral' },
              ],
              [
                { icon: 'sunflower', label: 'sunflower', bin: 'plant' },
                { icon: 'caterpillar', label: 'caterpillar', bin: 'animal' },
                { icon: 'tree', label: 'tree', bin: 'plant' },
                { icon: 'elephant', label: 'elephant', bin: 'animal' },
                { icon: 'mushroom', label: 'mushroom', bin: 'plant' },
                { icon: 'butterfly', label: 'butterfly', bin: 'animal' },
              ],
              'Plants are alive and usually stay in one place. Animals move around.',
            ),
          ],
        },
      ],
    },

    /* ================= UNIT 3 ================= */
    {
      id: 's-how',
      title: 'How Things Work',
      icon: 'microscope',
      tone: 'grape',
      lessons: [
        {
          id: 's-hot-cold',
          title: 'Hot & Cold',
          icon: 'thermometer',
          blurb: 'Sort things by temperature',
          tone: 'grape',
          teach: [
            teach('Hot and cold', 'We can feel how hot or cold something is with our hands. Fire is hot! Ice is cold!', 'thermometer'),
            teach('Hot things can burn', 'Fires, stoves and hot soup are very hot. We are careful around hot things!', 'fire'),
            teach('Cold things freeze', 'Ice cubes, snow and ice cream are frozen cold. Brrr!', 'iceCube'),
          ],
          steps: [
            sortStep(
              'Hot or cold? Sort them!',
              [
                { id: 'hot', label: 'Hot', icon: 'fire', tone: 'coral' },
                { id: 'cold', label: 'Cold', icon: 'iceCube', tone: 'sky' },
              ],
              [
                { icon: 'fire', label: 'fire', bin: 'hot' },
                { icon: 'iceCube', label: 'ice cube', bin: 'cold' },
                { icon: 'hotDrink', label: 'hot chocolate', bin: 'hot' },
                { icon: 'snowman', label: 'snowman', bin: 'cold' },
                { icon: 'soup', label: 'hot soup', bin: 'hot' },
                { icon: 'iceCream', label: 'ice cream', bin: 'cold' },
              ],
              'Hot things can burn us, cold things feel chilly. Our hands can tell the difference!',
            ),
            {
              id: sid('hot1'),
              kind: 'choice',
              prompt: 'What happens to ice when it gets warm?',
              say: 'What happens to ice when it gets warm?',
              hint: 'Think about a popsicle on a sunny day.',
              explain: 'Ice melts into water when it warms up. That is called melting!',
              options: pictureChoices({ icon: 'waterDrop', caption: 'it melts into water' }, [
                { icon: 'rock', caption: 'it turns into a rock' },
                { icon: 'rocket', caption: 'it flies away' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('hot2'),
              kind: 'choice',
              prompt: 'Which one keeps ice cream frozen?',
              say: 'Which place keeps ice cream frozen?',
              hint: 'Frozen means very cold.',
              explain: 'A freezer is very cold, so ice cream stays frozen there.',
              options: pictureChoices({ icon: 'iceCube', caption: 'the freezer' }, [
                { icon: 'sun', caption: 'in the sunshine' },
                { icon: 'fire', caption: 'next to a fire' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('hot3'),
              kind: 'choice',
              prompt: 'Which one would you wear on a very cold day?',
              say: 'Which one would you wear on a very cold day?',
              hint: 'Cold days need warm clothes.',
              explain: 'A warm coat keeps your body heat in on a cold day.',
              options: pictureChoices({ icon: 'coat', caption: 'a warm coat' }, [
                { icon: 'shorts', caption: 'shorts' },
                { icon: 'sunglasses', caption: 'sunglasses only' },
              ]),
              layout: 'grid-3',
            },
          ],
        },
        {
          id: 's-sink-float',
          title: 'Sink or Float',
          icon: 'bathtub',
          blurb: 'Will it float?',
          tone: 'grape',
          teach: [
            teach('Water holds some things up', 'Some things float on top of the water, and some sink down. Let us test them!', 'bathtub'),
            teach('Air helps things float', 'Things full of air float, like a beach ball or a rubber duck!', 'balloon'),
            teach('Heavy things sink', 'A rock is heavy and solid, so it sinks. Plop!', 'rock'),
          ],
          steps: [
            sortStep(
              'Drop them in the water! Sink or float?',
              [
                { id: 'float', label: 'Floats', icon: 'balloon', tone: 'sun' },
                { id: 'sink', label: 'Sinks', icon: 'rock', tone: 'grape' },
              ],
              [
                { icon: 'log', label: 'log', bin: 'float' },
                { icon: 'rock', label: 'rock', bin: 'sink' },
                { icon: 'lifeRing', label: 'life ring', bin: 'float' },
                { icon: 'key', label: 'key', bin: 'sink' },
                { icon: 'leafSingle', label: 'leaf', bin: 'float' },
                { icon: 'spoon', label: 'metal spoon', bin: 'sink' },
              ],
              'Light things with air inside float. Heavy, solid things sink.',
            ),
            {
              id: sid('sink1'),
              kind: 'choice',
              prompt: 'Why does a big heavy boat float?',
              say: 'Why does a big heavy boat float on the water?',
              hint: 'Look at whether there is air inside.',
              explain: 'A boat is hollow — it is full of air, so it floats!',
              options: pictureChoices({ icon: 'boat', caption: 'it is full of air' }, [
                { icon: 'rock', caption: 'it is made of stone' },
                { icon: 'fire', caption: 'it is hot' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('sink2'),
              kind: 'choice',
              prompt: 'Which one will float?',
              say: 'Which one will float on water?',
              hint: 'Think about which one is full of air.',
              explain: 'A beach ball is full of air, so it floats!',
              options: pictureChoices({ icon: 'volleyball', caption: 'beach ball' }, [
                { icon: 'rock', caption: 'big rock' },
                { icon: 'hammer', caption: 'hammer' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('sink3'),
              kind: 'choice',
              prompt: 'What is water like when it is frozen?',
              say: 'What is water like when it is frozen?',
              hint: 'Frozen water is hard and cold.',
              explain: 'Frozen water becomes solid ice. Ice is hard — water is runny!',
              options: shuffle([
                { id: sid('o'), icon: 'iceCube', caption: 'hard solid ice', correct: true },
                { id: sid('o'), icon: 'waterDrop', caption: 'runny liquid' },
                { id: sid('o'), icon: 'cloud', caption: 'fluffy cloud' },
              ]),
            },
          ],
        },

        {
          id: 's-bugs',
          title: 'Backyard Bugs',
          icon: 'ladybug',
          blurb: 'Meet the tiny creatures around you',
          tone: 'grape',
          teach: [
            teach('Bugs are everywhere!', 'Bugs are little animals with six legs. Ants, bees and ladybugs are all bugs!', 'ladybug'),
            teach('Bees make honey', 'Bees visit flowers to sip sweet nectar, and they turn it into honey inside their hive!', 'bee'),
            teach('Caterpillars transform', 'A caterpillar eats and eats, then sleeps in a cocoon — and wakes up as a butterfly!', 'caterpillar'),
          ],
          steps: [
            {
              id: sid('bug1'),
              kind: 'choice',
              prompt: 'Which bug makes honey?',
              say: 'Which bug makes sweet honey?',
              hint: 'It buzzes from flower to flower.',
              explain: 'Bees make honey from flower nectar. Yum!',
              options: pictureChoices({ icon: 'bee', caption: 'bee' }, [
                { icon: 'spider', caption: 'spider' },
                { icon: 'ant', caption: 'ant' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('bug2'),
              kind: 'choice',
              prompt: 'What does a caterpillar grow into?',
              say: 'A caterpillar sleeps in a cocoon and wakes up as what?',
              hint: 'It grows beautiful wings.',
              explain: 'A caterpillar becomes a butterfly! That is called metamorphosis.',
              options: pictureChoices({ icon: 'butterfly', caption: 'butterfly' }, [
                { icon: 'bird', caption: 'bird' },
                { icon: 'bee', caption: 'bee' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('bug3'),
              kind: 'choice',
              prompt: 'Which bug has red wings with black dots?',
              say: 'Which bug has red wings with black dots?',
              hint: 'It is a tiny good-luck beetle.',
              explain: 'A ladybug has shiny red wings with black dots!',
              options: pictureChoices({ icon: 'ladybug', caption: 'ladybug' }, [
                { icon: 'fly', caption: 'fly' },
                { icon: 'worm', caption: 'worm' },
              ]),
              layout: 'grid-3',
            },
            orderStep(
              'Put the butterfly story in order!',
              [
                { icon: 'egg', label: 'tiny egg', order: 1 },
                { icon: 'caterpillar', label: 'caterpillar', order: 2 },
                { icon: 'cocoon', label: 'cocoon', order: 3 },
                { icon: 'butterfly', label: 'butterfly', order: 4 },
              ],
              'Egg, caterpillar, cocoon, butterfly — the amazing life cycle!',
            ),
            {
              id: sid('bug4'),
              kind: 'choice',
              prompt: 'Why do worms help gardens?',
              say: 'Why are worms good for a garden?',
              hint: 'Worms wiggle through the dirt.',
              explain: 'Worms tunnel through the soil and mix it up, which helps plants grow!',
              options: wordChoices('They mix up the soil', ['They eat the plants', 'They chase the bugs']),
              layout: 'row',
            },
          ],
        },

        {
          id: 's-five-senses',
          title: 'My Five Senses',
          icon: 'eyes',
          blurb: 'See, hear, smell, taste and touch',
          tone: 'grape',
          teach: [
            teach('You have five senses!', 'Your senses help you learn about the world: seeing, hearing, smelling, tasting and touching!', 'eyes'),
            teach('Eyes see', 'Your eyes see colours, shapes and light. Blink blink!', 'eyes'),
            teach('Ears hear', 'Your ears hear music, birds and your favourite story!', 'musicNote'),
          ],
          steps: [
            {
              id: sid('sense1'),
              kind: 'choice',
              prompt: 'Which body part do you hear with?',
              say: 'Which body part do you hear with?',
              hint: 'Music goes in one ear and out the other!',
              explain: 'Your ears hear sounds — music, voices and giggles!',
              options: pictureChoices({ icon: 'mic', caption: 'ears' }, [
                { icon: 'hand', caption: 'hands' },
                { icon: 'nose', caption: 'nose' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('sense2'),
              kind: 'choice',
              prompt: 'Which sense uses your nose?',
              say: 'Which sense do you use your nose for?',
              hint: 'Fresh cookies do this to the whole house!',
              explain: 'Your nose smells things — like cookies baking!',
              options: wordChoices('smell', ['taste', 'seeing']),
              layout: 'row',
            },
            {
              id: sid('sense3'),
              kind: 'choice',
              prompt: 'You touch a teddy bear. Is it soft or hard?',
              say: 'You give a teddy bear a big hug. Is it soft or hard?',
              hint: 'Think about cuddling it.',
              explain: 'A teddy bear is soft and cuddly — perfect for hugging!',
              options: wordChoices('soft', ['hard', 'cold']),
              layout: 'row',
            },
            {
              id: sid('sense4'),
              kind: 'choice',
              prompt: 'Which sense tells you a lemon is sour?',
              say: 'Which sense tells you a lemon is sour?',
              hint: 'You use your tongue for this one!',
              explain: 'Your tongue tastes things. Lemons taste sour!',
              options: pictureChoices({ icon: 'lemon', caption: 'taste' }, [
                { icon: 'ear', caption: 'hearing' },
                { icon: 'hand', caption: 'touch' },
              ]),
              layout: 'grid-3',
            },
          ],
        },

        {
          id: 's-animal-babies',
          title: 'Animal Babies',
          icon: 'chick',
          blurb: 'Big animals and little ones',
          tone: 'grape',
          teach: [
            teach('Animals have babies', 'Baby animals grow up to look like their parents. A chick grows into a hen!', 'chick'),
            teach('Puppies and kittens', 'A dog has puppies. A cat has kittens. Baby animals need lots of care!', 'dog'),
            teach('Tadpoles become frogs', 'A frog lays eggs in the pond. The eggs hatch into tadpoles that grow into frogs!', 'frog'),
          ],
          steps: [
            {
              id: sid('ab1'),
              kind: 'match',
              prompt: 'Match each mom with her baby!',
              say: 'Match each mom animal with her baby.',
              hint: 'Think about which baby belongs to which animal.',
              explain: 'Hens have chicks, dogs have puppies and cats have kittens!',
              pairs: [
                { left: 'hen', right: 'chick' },
                { left: 'dog', right: 'puppy' },
                { left: 'cat', right: 'kitten' },
              ],
            },
            {
              id: sid('ab2'),
              kind: 'choice',
              prompt: 'What is a baby frog called?',
              say: 'What is a baby frog called before it grows legs?',
              hint: 'It swims and has a long tail.',
              explain: 'A tadpole! It swims like a little fish, then grows into a frog.',
              options: pictureChoices({ icon: 'frog', caption: 'tadpole' }, [
                { icon: 'caterpillar', caption: 'caterpillar' },
                { icon: 'worm', caption: 'worm' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('ab3'),
              kind: 'choice',
              prompt: 'What do baby animals need from their parents?',
              say: 'What do baby animals need from their parents?',
              hint: 'Think about what YOU needed as a baby.',
              explain: 'Baby animals need food, warmth and protection — just like you did!',
              options: wordChoices('food and care', ['keys and a phone', 'homework']),
              layout: 'row',
            },
            {
              id: sid('ab4'),
              kind: 'choice',
              prompt: 'A baby dog is called a…',
              say: 'A baby dog is called a what?',
              hint: 'P is for this baby animal!',
              explain: 'A puppy! Baby dogs are called puppies.',
              options: wordChoices('puppy', ['kitten', 'chick']),
              layout: 'row',
            },
          ],
        },

        {
          id: 's-materials',
          title: 'What Things Are Made Of',
          icon: 'cube',
          blurb: 'Wood, metal, glass and cloth',
          tone: 'grape',
          teach: [
            teach('Everything is made of something', 'Look around! Tables are made of wood. Windows are made of glass. Everything has a material.', 'cube'),
            teach('Wood comes from trees', 'Wood is strong and comes from trees. Tables, chairs and spoons can be wood!', 'tree'),
            teach('Cloth comes soft', 'Cloth is soft and bendy — perfect for t-shirts and blankets!', 'coat'),
          ],
          steps: [
            sortStep(
              'Sort by material!',
              [
                { id: 'wood', label: 'Wood', icon: 'log', tone: 'grass' },
                { id: 'metal', label: 'Metal', icon: 'key', tone: 'sky' },
              ],
              [
                { icon: 'house', label: 'wooden door', bin: 'wood' },
                { icon: 'key', label: 'metal key', bin: 'metal' },
                { icon: 'pencil', label: 'wooden pencil', bin: 'wood' },
                { icon: 'spoon', label: 'metal spoon', bin: 'metal' },
                { icon: 'hammer', label: 'hammer', bin: 'metal' },
                { icon: 'tree', label: 'tree trunk', bin: 'wood' },
              ],
              'Wood comes from trees. Metal is shiny and strong, dug from the ground!',
            ),
            {
              id: sid('mat1'),
              kind: 'choice',
              prompt: 'Which one is best for a window?',
              say: 'Which material is best for a window?',
              hint: 'You want to see through it!',
              explain: 'Glass is see-through, so light comes in and you can look out!',
              options: wordChoices('glass', ['wood', 'rock']),
              layout: 'row',
            },
            {
              id: sid('mat2'),
              kind: 'choice',
              prompt: 'Which one is best for a blanket?',
              say: 'Which material is best for a cosy blanket?',
              hint: 'It should be soft and warm.',
              explain: 'Cloth is soft and warm — perfect for snuggling!',
              options: wordChoices('cloth', ['metal', 'glass']),
              layout: 'row',
            },
            {
              id: sid('mat3'),
              kind: 'choice',
              prompt: 'Why do we make hammers from metal?',
              say: 'Why do we make hammers from metal?',
              hint: 'Hammers hit things hard.',
              explain: 'Metal is hard and strong — it can bang and not break!',
              options: wordChoices('metal is strong', ['metal is soft', 'metal is see-through']),
              layout: 'row',
            },
          ],
        },

        {
          id: 's-seasons',
          title: 'The Four Seasons',
          icon: 'calendar',
          blurb: 'Spring, summer, fall, winter',
          tone: 'grape',
          teach: [
            teach('A year has four seasons', 'Spring, summer, fall and winter take turns every year. Each season feels different!', 'calendar'),
            teach('Spring brings blossoms', 'In spring, flowers bloom and baby animals are born. The world wakes up!', 'blossom'),
            teach('Winter brings snow', 'In winter it gets cold. Some places get snow — perfect for snowmen!', 'snowman'),
          ],
          steps: [
            sortStep(
              'Sort these into the right season!',
              [
                { id: 'summer', label: 'Summer', icon: 'sun', tone: 'sun' },
                { id: 'winter', label: 'Winter', icon: 'snowflake', tone: 'sky' },
              ],
              [
                { icon: 'iceCream', label: 'ice cream', bin: 'summer' },
                { icon: 'snowman', label: 'snowman', bin: 'winter' },
                { icon: 'swimsuit', label: 'swimsuit', bin: 'summer' },
                { icon: 'mitten', label: 'mittens', bin: 'winter' },
                { icon: 'sunglasses', label: 'sunglasses', bin: 'summer' },
                { icon: 'scarf', label: 'warm scarf', bin: 'winter' },
              ],
              'Summer is hot and wintry weather is cold. We dress differently for each!',
            ),
            {
              id: sid('seas1'),
              kind: 'choice',
              prompt: 'In which season do flowers bloom?',
              say: 'In which season do flowers start to bloom?',
              hint: 'It comes after winter.',
              explain: 'Spring! The weather warms up and flowers bloom everywhere.',
              options: pictureChoices({ icon: 'blossom', caption: 'spring' }, [
                { icon: 'snowflake', caption: 'winter' },
                { icon: 'mapleLeaf', caption: 'fall' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('seas2'),
              kind: 'choice',
              prompt: 'In which season do leaves fall down?',
              say: 'In which season do leaves change colour and fall?',
              hint: 'It is named after what the leaves do!',
              explain: 'Fall! Leaves turn red, orange and yellow, then drift down.',
              options: pictureChoices({ icon: 'mapleLeaf', caption: 'fall' }, [
                { icon: 'blossom', caption: 'spring' },
                { icon: 'sun', caption: 'summer' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('seas3'),
              kind: 'choice',
              prompt: 'Which clothes do we wear in summer?',
              say: 'Which clothes do we wear when it is hot?',
              hint: 'Light clothes keep us cool.',
              explain: 'Shorts and t-shirts keep us cool in the summer heat!',
              options: pictureChoices({ icon: 'shorts', caption: 'shorts' }, [
                { icon: 'mitten', caption: 'mittens' },
                { icon: 'coat', caption: 'heavy coat' },
              ]),
              layout: 'grid-3',
            },
          ],
        },

        {
          id: 's-recycle',
          title: 'Reduce, Reuse, Recycle',
          icon: 'refresh',
          blurb: 'Taking care of trash the smart way',
          tone: 'grape',
          teach: [
            teach('Trash can have a second life', 'Some trash can be recycled — melted or cleaned and made into something new!', 'refresh'),
            teach('Paper becomes new paper', 'Old paper can be recycled into fresh paper for drawing!', 'notebook'),
            teach('Reuse before you toss', 'A jar can hold crayons. A box can be a car. Reusing is fun!', 'gift'),
          ],
          steps: [
            {
              id: sid('rec1'),
              kind: 'choice',
              prompt: 'What does recycle mean?',
              say: 'What does it mean to recycle?',
              hint: 'It is about making old things new again.',
              explain: 'Recycling means turning old things into something new instead of throwing them away!',
              options: wordChoices('make old things into new things', ['throw everything in the ocean', 'bury trash in the garden']),
              layout: 'row',
            },
            sortStep(
              'Sort: recycle or trash!',
              [
                { id: 'recycle', label: 'Recycle', icon: 'refresh', tone: 'grass' },
                { id: 'trash', label: 'Trash', icon: 'trash', tone: 'coral' },
              ],
              [
                { icon: 'notebook', label: 'old paper', bin: 'recycle' },
                { icon: 'apple', label: 'apple core', bin: 'trash' },
                { icon: 'gift', label: 'cardboard box', bin: 'recycle' },
                { icon: 'pizza', label: 'greasy pizza box', bin: 'trash' },
                { icon: 'book', label: 'old magazine', bin: 'recycle' },
                { icon: 'candy', label: 'candy wrapper', bin: 'trash' },
              ],
              'Paper and cardboard can be recycled. Food scraps and greasy things go in the trash!',
            ),
            {
              id: sid('rec2'),
              kind: 'choice',
              prompt: 'What can an empty jar become?',
              say: 'What can an empty jar become instead of trash?',
              hint: 'It can hold your pencils or crayons!',
              explain: 'A jar can be reused as a pencil holder — reduce, reuse, recycle!',
              options: pictureChoices({ icon: 'pencil', caption: 'a pencil holder' }, [
                { icon: 'trash', caption: 'just trash' },
                { icon: 'fire', caption: 'fuel for a fire' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('rec3'),
              kind: 'choice',
              prompt: 'Why is recycling good for the Earth?',
              say: 'Why is recycling good for the Earth?',
              hint: 'Think about using less new stuff.',
              explain: 'Recycling means we use fewer new materials, so the Earth stays cleaner!',
              options: wordChoices('It keeps Earth clean and saves materials', ['It makes more trash', 'It is just for fun']),
              layout: 'row',
            },
          ],
        },

        {
          id: 'shadows',
          title: 'Light & Shadows',
          icon: 'sun',
          blurb: 'How shadows are made',
          tone: 'grape',
          teach: [
            teach('Light makes shadows', 'When light shines on something and cannot get through, a dark shadow appears behind it!', 'sun'),
            teach('Shadows move with the sun', 'In the morning your shadow is long. At noon it is short. Watch it change!', 'sunset'),
            teach('Play with shadows', 'You can make shadow animals with your hands and a flashlight. Try a bunny!', 'flashlight'),
          ],
          steps: [
            {
              id: sid('sh1'),
              kind: 'choice',
              prompt: 'What do you need to make a shadow?',
              say: 'What do you need to make a shadow?',
              hint: 'It is bright and shines on things.',
              explain: 'You need light! No light, no shadow.',
              options: pictureChoices({ icon: 'flashlight', caption: 'light' }, [
                { icon: 'waterDrop', caption: 'water' },
                { icon: 'musicNote', caption: 'music' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('sh2'),
              kind: 'choice',
              prompt: 'When is your shadow the shortest?',
              say: 'When is your shadow the shortest?',
              hint: 'Think about when the sun is highest in the sky.',
              explain: 'At noon! The sun is right above you, so your shadow is short.',
              options: wordChoices('at noon', ['in the morning', 'at bedtime']),
              layout: 'row',
            },
            {
              id: sid('sh3'),
              kind: 'choice',
              prompt: 'What does a shadow look like?',
              say: 'What does a shadow look like?',
              hint: 'It is the shape of the thing, but dark.',
              explain: 'A shadow is a dark copy of the shape of the thing!',
              options: wordChoices('a dark shape copy', ['a rainbow', 'a bright picture']),
              layout: 'row',
            },
            {
              id: sid('sh4'),
              kind: 'choice',
              prompt: 'Which one lets light shine through?',
              say: 'Which one lets light shine through it?',
              hint: 'You can see through it too.',
              explain: 'Glass lets light through — that is why windows are made of it! A rock does not.',
              options: pictureChoices({ icon: 'iceCube', caption: 'glass' }, [
                { icon: 'rock', caption: 'rock' },
                { icon: 'log', caption: 'wood' },
              ]),
              layout: 'grid-3',
            },
          ],
        },
      ],
    },
  ],
}
