import type { Subject } from '../types'
import {
  matchStep,
  orderStep,
  pictureChoices,
  sid,
  sortStep,
  teach,
  wordChoices,
} from './builders'

/* ============================================================
   SOCIAL STUDIES — Me, my family, my community and my world.
   First graders learn who they are, how people live together,
   and what the great big world looks like.
   ============================================================ */

export const social: Subject = {
  id: 'social',
  name: 'Social Studies',
  icon: 'compass',
  tagline: 'People, places and our big world',
  tone: 'grape',
  strands: ['Me & My Family', 'Community Helpers', 'Maps & Places', 'Our World'],
  units: [
    /* ================= UNIT 1 ================= */
    {
      id: 'so-me',
      title: 'Me & My Family',
      icon: 'family',
      tone: 'berry',
      lessons: [
        {
          id: 'so-family',
          title: 'My Family',
          icon: 'family',
          blurb: 'Who is in a family?',
          tone: 'berry',
          teach: [
            teach('Families are teams', 'A family is a group of people who love and take care of each other. Every family is different!', 'family'),
            teach('Who lives with you?', 'Families can have moms, dads, sisters, brothers, grandmas and grandpas. Big or small, families are special!', 'teddy'),
          ],
          steps: [
            {
              id: sid('fam1'),
              kind: 'choice',
              prompt: 'Who takes care of you at home?',
              say: 'Who takes care of you at home?',
              hint: 'Think about the people who love you.',
              explain: 'Family members take care of each other with love!',
              options: pictureChoices({ icon: 'family', caption: 'my family' }, [
                { icon: 'rocket', caption: 'a rocket' },
                { icon: 'rock', caption: 'a rock' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('fam2'),
              kind: 'choice',
              prompt: 'What does a family give you?',
              say: 'What does a family give you?',
              hint: 'Families give things you cannot hold in your hands.',
              explain: 'Families give love, hugs and help — the most important things!',
              options: wordChoices('love and care', ['only toys', 'only snacks']),
              layout: 'row',
            },
            {
              id: sid('fam3'),
              kind: 'choice',
              prompt: 'Which one is a family activity?',
              say: 'Which one is something families do together?',
              hint: 'Which one has people doing something together?',
              explain: 'Eating dinner together is a family activity!',
              options: pictureChoices({ icon: 'pizza', caption: 'eat dinner together' }, [
                { icon: 'tv', caption: 'watch TV alone' },
                { icon: 'bed', caption: 'sleep all day' },
              ]),
              layout: 'grid-3',
            },
            sortStep(
              'Sort: family members and pets!',
              [
                { id: 'people', label: 'People', icon: 'family', tone: 'berry' },
                { id: 'pets', label: 'Pets', icon: 'pawPrints', tone: 'sky' },
              ],
              [
                { icon: 'family', label: 'family', bin: 'people' },
                { icon: 'dog', label: 'dog', bin: 'pets' },
                { icon: 'baby', label: 'baby', bin: 'people' },
                { icon: 'cat', label: 'cat', bin: 'pets' },
                { icon: 'person', label: 'grandpa', bin: 'people' },
                { icon: 'rabbit', label: 'bunny', bin: 'pets' },
              ],
              'People and pets both live at home, but people are family members and animals are pets!',
            ),
          ],
        },
        {
          id: 'so-rules',
          title: 'Rules Keep Us Safe',
          icon: 'shield',
          blurb: 'Why we have rules',
          tone: 'berry',
          teach: [
            teach('Rules help everyone', 'Rules are promises we keep so everyone can be safe and have fun!', 'shield'),
            teach('Look both ways', 'Before crossing the street, we stop, look left, look right, then listen!', 'bus'),
          ],
          steps: [
            {
              id: sid('rule1'),
              kind: 'choice',
              prompt: 'Why do we look both ways before crossing?',
              say: 'Why do we look both ways before crossing the street?',
              hint: 'What might be driving on the road?',
              explain: 'We look both ways so we can see cars and cross safely!',
              options: wordChoices('to see cars and stay safe', ['to count the cars', 'because it is fun']),
              layout: 'row',
            },
            {
              id: sid('rule2'),
              kind: 'choice',
              prompt: 'What should you do when the bus arrives?',
              say: 'What should you do when the school bus arrives?',
              hint: 'Running could cause an accident.',
              explain: 'We wait calmly in line and take turns getting on the bus!',
              options: pictureChoices({ icon: 'bus', caption: 'wait in line' }, [
                { icon: 'rocket', caption: 'run fast' },
                { icon: 'party', caption: 'jump and shout' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('rule3'),
              kind: 'choice',
              prompt: 'A friend has the toy you want. What do you do?',
              say: 'A friend is playing with a toy you want. What do you do?',
              hint: 'Think about what a good friend would do.',
              explain: 'We ask nicely and take turns. That keeps everyone happy!',
              options: wordChoices('ask nicely for a turn', ['grab it', 'hide it']),
              layout: 'row',
            },
            {
              id: sid('rule4'),
              kind: 'choice',
              prompt: 'Which one is a safety rule?',
              say: 'Which one is a safety rule?',
              hint: 'Safety rules keep our bodies safe.',
              explain: 'Wearing a helmet protects your head when you ride!',
              options: pictureChoices({ icon: 'ball', caption: 'wear a helmet when riding' }, [
                { icon: 'candy', caption: 'eat candy all day' },
                { icon: 'tv', caption: 'watch TV all night' },
              ]),
              layout: 'grid-3',
            },
          ],
        },
        {
          id: 'so-feelings',
          title: 'Feelings',
          icon: 'smiley',
          blurb: 'Happy, sad, mad and glad',
          tone: 'berry',
          teach: [
            teach('Feelings have names', 'Happy, sad, angry, scared and excited are feelings. All feelings are okay!', 'smiley'),
            teach('Faces show feelings', 'A big smile means happy. Tears can mean sad. Look at faces to see how friends feel!', 'happyFace'),
          ],
          steps: [
            {
              id: sid('feel1'),
              kind: 'choice',
              prompt: 'You get a surprise present. How do you feel?',
              say: 'You get a surprise present! How do you feel?',
              hint: 'A surprise gift makes you want to jump up!',
              explain: 'Excited! Surprises make us feel bouncy and happy.',
              options: wordChoices('excited and happy', ['angry', 'sleepy']),
              layout: 'row',
            },
            {
              id: sid('feel2'),
              kind: 'choice',
              prompt: 'Your friend is crying. What can you do?',
              say: 'Your friend is crying. What can you do to help?',
              hint: 'Think about what would help YOU feel better.',
              explain: 'Asking "are you okay?" and staying with them helps a friend feel better!',
              options: wordChoices('ask if they are okay', ['walk away', 'laugh']),
              layout: 'row',
            },
            {
              id: sid('feel3'),
              kind: 'choice',
              prompt: 'What can you do when you feel angry?',
              say: 'What can you do when you feel angry?',
              hint: 'Big breaths can calm big feelings.',
              explain: 'Taking deep breaths and telling a grown-up helps angry feelings shrink!',
              options: wordChoices('take deep breaths', ['hit someone', 'scream all day']),
              layout: 'row',
            },
            matchStep(
              'Match the feeling to the picture!',
              [
                { left: 'smiley', right: 'sunHappy', leftLabel: 'happy', rightLabel: 'sunny' },
                { left: 'happyFace', right: 'moonSleep', leftLabel: 'calm', rightLabel: 'sleepy' },
                { left: 'party', right: 'fireworks', leftLabel: 'excited', rightLabel: 'celebrate' },
              ],
              'Happy like sunshine, calm like bedtime, excited like fireworks!',
            ),
          ],
        },
        {
          id: 'so-friends',
          title: 'Being a Good Friend',
          icon: 'heart',
          blurb: 'Sharing and caring',
          tone: 'berry',
          teach: [
            teach('Friends make life fun', 'Good friends share, take turns and help each other. Being kind makes friends happy!', 'heart'),
            teach('Sharing is caring', 'When you share your toys, everyone gets to play. Two smiles are better than one!', 'teddy'),
          ],
          steps: [
            {
              id: sid('fr1'),
              kind: 'choice',
              prompt: 'How do you make a new friend?',
              say: 'How do you make a new friend?',
              hint: 'What would you want someone to say to you?',
              explain: 'Smile, say hello and ask their name. That is how friendships start!',
              options: wordChoices('smile and say hello', ['hide from them', 'take their toys']),
              layout: 'row',
            },
            {
              id: sid('fr2'),
              kind: 'choice',
              prompt: 'Your friend forgot their snack. What is a kind thing to do?',
              say: 'Your friend forgot their snack. What is a kind thing to do?',
              hint: 'Sharing means everyone gets some.',
              explain: 'Sharing your snack shows you care about your friend!',
              options: pictureChoices({ icon: 'apple', caption: 'share your snack' }, [
                { icon: 'trash', caption: 'throw it away' },
                { icon: 'lock', caption: 'hide your snack' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('fr3'),
              kind: 'choice',
              prompt: 'Someone broke your crayon by accident. What do you say?',
              say: 'Someone broke your crayon by accident. What do you say?',
              hint: 'Accidents happen to everyone.',
              explain: '"That is okay, accidents happen!" Forgiving words keep friendships strong.',
              options: wordChoices('That is okay!', ['You are in big trouble!', 'I am telling everyone!']),
              layout: 'row',
            },
          ],
        },
      ],
    },

    /* ================= UNIT 2 ================= */
    {
      id: 'so-community',
      title: 'My Community',
      icon: 'house',
      tone: 'sun',
      lessons: [
        {
          id: 'so-helpers',
          title: 'Community Helpers',
          icon: 'family',
          blurb: 'People who help us every day',
          tone: 'sun',
          teach: [
            teach('Helpers all around', 'Some jobs are all about helping people: firefighters, doctors, teachers and police officers!', 'shield'),
            teach('Firefighters', 'Firefighters spray water on fires and rescue people. They ride a big red truck!', 'fire'),
            teach('Doctors', 'Doctors help us get better when we are sick. They listen to our hearts with a stethoscope!', 'heart'),
          ],
          steps: [
            {
              id: sid('help1'),
              kind: 'choice',
              prompt: 'Who puts out fires?',
              say: 'Who puts out fires?',
              hint: 'They ride a big red truck with a ladder.',
              explain: 'Firefighters put out fires and rescue people. Hero helpers!',
              options: pictureChoices({ icon: 'fireworks', caption: 'firefighter' }, [
                { icon: 'pizza', caption: 'chef' },
                { icon: 'backpack', caption: 'student' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('help2'),
              kind: 'choice',
              prompt: 'Who teaches you at school?',
              say: 'Who teaches you at school?',
              hint: 'They read stories and help you learn.',
              explain: 'Teachers help us learn to read, write and count!',
              options: pictureChoices({ icon: 'book', caption: 'teacher' }, [
                { icon: 'elephant', caption: 'elephant' },
                { icon: 'rocket', caption: 'astronaut' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('help3'),
              kind: 'choice',
              prompt: 'Who delivers letters to your mailbox?',
              say: 'Who delivers letters to your mailbox?',
              hint: 'They drive a little white truck full of mail.',
              explain: 'The mail carrier brings letters and packages to every house!',
              options: pictureChoices({ icon: 'backpack', caption: 'mail carrier' }, [
                { icon: 'bus', caption: 'bus driver' },
                { icon: 'fish', caption: 'fisher' },
              ]),
              layout: 'grid-3',
            },
            matchStep(
              'Match each helper with their tool!',
              [
                { left: 'fireworks', right: 'waterDrop', leftLabel: 'firefighter', rightLabel: 'water hose' },
                { left: 'book', right: 'pencil', leftLabel: 'teacher', rightLabel: 'pencil' },
                { left: 'heart', right: 'medal', leftLabel: 'doctor', rightLabel: 'helping badge' },
              ],
              'Every helper has special tools for their important job!',
            ),
          ],
        },
        {
          id: 'so-places',
          title: 'Places in Town',
          icon: 'house',
          blurb: 'Where people go in a community',
          tone: 'sun',
          teach: [
            teach('Communities have places', 'Towns have special places: the library for books, the park for playing, the store for food!', 'house'),
            teach('The library', 'At the library you can borrow books for free and hear story time!', 'book'),
          ],
          steps: [
            {
              id: sid('place1'),
              kind: 'choice',
              prompt: 'Where do you go to borrow books?',
              say: 'Where do you go to borrow books to read?',
              hint: 'It is quiet and full of bookshelves.',
              explain: 'The library! You can borrow books and bring them back when you finish.',
              options: pictureChoices({ icon: 'book', caption: 'the library' }, [
                { icon: 'pizza', caption: 'the pizza shop' },
                { icon: 'car', caption: 'the car wash' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('place2'),
              kind: 'choice',
              prompt: 'Where do families buy food?',
              say: 'Where do families go to buy food?',
              hint: 'It has carts and aisles of groceries.',
              explain: 'The grocery store! That is where we shop for food.',
              options: pictureChoices({ icon: 'apple', caption: 'grocery store' }, [
                { icon: 'school', caption: 'school' },
                { icon: 'bathtub', caption: 'bathtub' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('place3'),
              kind: 'choice',
              prompt: 'Where do you play on swings and slides?',
              say: 'Where do you play on swings and slides?',
              hint: 'It is outside and has playgrounds.',
              explain: 'The park! Swings, slides and space to run.',
              options: pictureChoices({ icon: 'hills', caption: 'the park' }, [
                { icon: 'bed', caption: 'bedroom' },
                { icon: 'bus', caption: 'bus stop' },
              ]),
              layout: 'grid-3',
            },
            sortStep(
              'Sort: where do these things belong?',
              [
                { id: 'read', label: 'Library', icon: 'book', tone: 'sky' },
                { id: 'health', label: 'Hospital', icon: 'heart', tone: 'coral' },
              ],
              [
                { icon: 'book', label: 'storybooks', bin: 'read' },
                { icon: 'heart', label: 'getting better', bin: 'health' },
                { icon: 'notebook', label: 'quiet reading', bin: 'read' },
                { icon: 'medal', label: 'helping doctors', bin: 'health' },
                { icon: 'eyes', label: 'reading time', bin: 'read' },
                { icon: 'shield', label: 'nurses and doctors', bin: 'health' },
              ],
              'Libraries are for books and quiet. Hospitals are for helping people get better!',
            ),
          ],
        },
        {
          id: 'so-jobs',
          title: 'Jobs People Do',
          icon: 'hammer',
          blurb: 'Every job is important',
          tone: 'sun',
          teach: [
            teach('People work at jobs', 'Grown-ups have jobs. Some bake bread, some build houses, some drive buses. Every job matters!', 'hammer'),
            teach('Bakers bake bread', 'Bakers wake up early to bake warm bread and yummy cakes!', 'cake'),
          ],
          steps: [
            {
              id: sid('job1'),
              kind: 'choice',
              prompt: 'Who bakes bread and cakes?',
              say: 'Who bakes bread and cakes?',
              hint: 'Their kitchen smells amazing!',
              explain: 'A baker bakes bread, cakes and cookies!',
              options: pictureChoices({ icon: 'cake', caption: 'baker' }, [
                { icon: 'car', caption: 'driver' },
                { icon: 'fish', caption: 'fisher' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('job2'),
              kind: 'choice',
              prompt: 'Who drives the school bus?',
              say: 'Who drives you to school on the bus?',
              hint: 'They steer a big yellow vehicle.',
              explain: 'The bus driver takes kids to school safely every day!',
              options: pictureChoices({ icon: 'bus', caption: 'bus driver' }, [
                { icon: 'cake', caption: 'baker' },
                { icon: 'pencil', caption: 'writer' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('job3'),
              kind: 'choice',
              prompt: 'Who grows vegetables on a farm?',
              say: 'Who grows vegetables on a farm?',
              hint: 'They work with plants and animals.',
              explain: 'A farmer grows vegetables and takes care of farm animals!',
              options: pictureChoices({ icon: 'carrot', caption: 'farmer' }, [
                { icon: 'mic', caption: 'singer' },
                { icon: 'rocket', caption: 'astronaut' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('job4'),
              kind: 'choice',
              prompt: 'Which job helps keep the town clean?',
              say: 'Which job helps keep the town clean?',
              hint: 'They drive a special truck that collects trash.',
              explain: 'Trash collectors keep our town clean and healthy!',
              options: pictureChoices({ icon: 'trash', caption: 'trash collector' }, [
                { icon: 'paint', caption: 'painter' },
                { icon: 'musicNote', caption: 'musician' },
              ]),
              layout: 'grid-3',
            },
          ],
        },
      ],
    },

    /* ================= UNIT 3 ================= */
    {
      id: 'so-maps',
      title: 'Maps & Places',
      icon: 'map',
      tone: 'sky',
      lessons: [
        {
          id: 'so-maps-intro',
          title: 'What Is a Map?',
          icon: 'map',
          blurb: 'Pictures that show places',
          tone: 'sky',
          teach: [
            teach('Maps show where things are', 'A map is a drawing of a place seen from way up high, like a bird! It shows where things are.', 'map'),
            teach('Symbols stand for places', 'Maps use tiny pictures called symbols. A little house can mean a home!', 'compass'),
          ],
          steps: [
            {
              id: sid('map1'),
              kind: 'choice',
              prompt: 'What does a map show?',
              say: 'What does a map show us?',
              hint: 'Think about finding treasure!',
              explain: 'A map shows where places are — like a picture of the world from above!',
              options: wordChoices('where places are', ['what food tastes like', 'how to sing']),
              layout: 'row',
            },
            {
              id: sid('map2'),
              kind: 'choice',
              prompt: 'Which tool helps you find north?',
              say: 'Which tool always points to the north?',
              hint: 'It has a spinning needle and helps explorers.',
              explain: 'A compass! Its needle always points north.',
              options: pictureChoices({ icon: 'compass', caption: 'compass' }, [
                { icon: 'spoon', caption: 'spoon' },
                { icon: 'clock', caption: 'clock' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('map3'),
              kind: 'choice',
              prompt: 'You want to find the school on a map. What do you look for?',
              say: 'You want to find the school on a map. What do you look for?',
              hint: 'Maps use little pictures of buildings.',
              explain: 'Look for the school symbol — maps use pictures to stand for real places!',
              options: pictureChoices({ icon: 'school', caption: 'the school symbol' }, [
                { icon: 'iceCream', caption: 'ice cream symbol' },
                { icon: 'dog', caption: 'dog symbol' },
              ]),
              layout: 'grid-3',
            },
          ],
        },
        {
          id: 'so-landmarks',
          title: 'Home, School & Town',
          icon: 'school',
          blurb: 'Places in your day',
          tone: 'sky',
          teach: [
            teach('Your day has places', 'You sleep at home, learn at school, and play at the park. Everyone has places in their day!', 'school'),
            teach('School is a special place', 'At school we learn, play with friends and eat lunch. Teachers help us!', 'notebook'),
          ],
          steps: [
            {
              id: sid('land1'),
              kind: 'choice',
              prompt: 'Where do you sleep and eat with your family?',
              say: 'Where do you sleep and eat meals with your family?',
              hint: 'It is where you live!',
              explain: 'Home! That is where our day starts and ends.',
              options: pictureChoices({ icon: 'house', caption: 'home' }, [
                { icon: 'bus', caption: 'bus' },
                { icon: 'rocket', caption: 'rocket' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('land2'),
              kind: 'choice',
              prompt: 'Where do you go to learn and play with friends?',
              say: 'Where do you go to learn and play with friends?',
              hint: 'You carry a backpack there.',
              explain: 'School! That is where learning happens.',
              options: pictureChoices({ icon: 'backpack', caption: 'school' }, [
                { icon: 'bathtub', caption: 'bathtub' },
                { icon: 'bed', caption: 'bed' },
              ]),
              layout: 'grid-3',
            },
            orderStep(
              'Put the school day in order!',
              [
                { icon: 'bus', label: 'ride to school', order: 1 },
                { icon: 'book', label: 'read and learn', order: 2 },
                { icon: 'pizza', label: 'eat lunch', order: 3 },
                { icon: 'house', label: 'go home', order: 4 },
              ],
              'Ride to school, learn, eat lunch, then go home. That is a school day!',
            ),
          ],
        },
        {
          id: 'so-transport',
          title: 'Ways to Travel',
          icon: 'car',
          blurb: 'Cars, buses, boats and planes',
          tone: 'sky',
          teach: [
            teach('So many ways to go!', 'People travel by car, bus, bike, boat, train and plane. Wheels, sails and wings!', 'car'),
            teach('Boats float on water', 'Boats travel on water. Some have sails that catch the wind!', 'boat'),
          ],
          steps: [
            {
              id: sid('trans1'),
              kind: 'choice',
              prompt: 'Which one travels on water?',
              say: 'Which one travels on water?',
              hint: 'It floats and has a captain.',
              explain: 'A boat travels on water — rivers, lakes and oceans!',
              options: pictureChoices({ icon: 'boat', caption: 'boat' }, [
                { icon: 'bicycle', caption: 'bicycle' },
                { icon: 'car', caption: 'car' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('trans2'),
              kind: 'choice',
              prompt: 'Which one has two wheels and pedals?',
              say: 'Which one has two wheels and pedals you push with your feet?',
              hint: 'You wear a helmet when you ride it.',
              explain: 'A bicycle! Pedal power makes the wheels go round.',
              options: pictureChoices({ icon: 'bicycle', caption: 'bicycle' }, [
                { icon: 'boat', caption: 'boat' },
                { icon: 'rocket', caption: 'rocket' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('trans3'),
              kind: 'choice',
              prompt: 'Which one is the fastest way to cross the ocean?',
              say: 'Which one is the fastest way to cross the ocean?',
              hint: 'It flies high in the sky.',
              explain: 'An airplane! Planes fly over the ocean faster than boats sail.',
              options: pictureChoices({ icon: 'rocket', caption: 'airplane' }, [
                { icon: 'boat', caption: 'sailboat' },
                { icon: 'turtle', caption: 'turtle' },
              ]),
              layout: 'grid-3',
            },
            sortStep(
              'Sort by where they travel!',
              [
                { id: 'land', label: 'On land', icon: 'car', tone: 'grass' },
                { id: 'air', label: 'In the sky', icon: 'rocket', tone: 'sky' },
              ],
              [
                { icon: 'bus', label: 'bus', bin: 'land' },
                { icon: 'rocket', label: 'airplane', bin: 'air' },
                { icon: 'bicycle', label: 'bicycle', bin: 'land' },
                { icon: 'kite', label: 'kite', bin: 'air' },
                { icon: 'car', label: 'car', bin: 'land' },
                { icon: 'bird', label: 'bird', bin: 'air' },
              ],
              'Buses and cars roll on land. Planes, kites and birds fly in the sky!',
            ),
          ],
        },
      ],
    },

    /* ================= UNIT 4 ================= */
    {
      id: 'so-world',
      title: 'Our World',
      icon: 'earth',
      tone: 'grass',
      lessons: [
        {
          id: 'so-earth',
          title: 'Our Big World',
          icon: 'earth',
          blurb: 'The planet we all share',
          tone: 'grass',
          teach: [
            teach('Earth is our home', 'The Earth is a giant ball floating in space. Everyone you know lives here together!', 'earth'),
            teach('Land and water', 'Earth has land to live on and lots of water: oceans, lakes and rivers!', 'wave'),
            teach('Many countries, one world', 'People live in countries all over the world, and we all share the same big planet!', 'planet'),
          ],
          steps: [
            {
              id: sid('earth1'),
              kind: 'choice',
              prompt: 'What is the name of our planet?',
              say: 'What is the name of the planet we all live on?',
              hint: 'It sounds like the ground beneath your feet.',
              explain: 'Earth! It is the planet we all share.',
              options: wordChoices('Earth', ['Mars', 'the Sun']),
              layout: 'row',
            },
            {
              id: sid('earth2'),
              kind: 'choice',
              prompt: 'What covers most of the Earth?',
              say: 'What covers most of the Earth: land or water?',
              hint: 'Think about how much is blue from space.',
              explain: 'Water covers most of Earth — that is why it looks blue from space!',
              options: pictureChoices({ icon: 'wave', caption: 'water' }, [
                { icon: 'house', caption: 'houses' },
                { icon: 'car', caption: 'roads' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('earth3'),
              kind: 'choice',
              prompt: 'Do people around the world look and live exactly the same?',
              say: 'Do people all around the world look and live exactly the same?',
              hint: 'Think about different languages, foods and clothes.',
              explain: 'People are wonderfully different — different languages, foods and traditions!',
              options: wordChoices('No, everyone is different', ['Yes, all the same', 'Only on Mondays']),
              layout: 'row',
            },
          ],
        },
        {
          id: 'so-weather-helpers',
          title: 'Caring for the Earth',
          icon: 'sprout',
          blurb: 'Keep our planet happy',
          tone: 'grass',
          teach: [
            teach('Earth needs our help', 'The Earth gives us air, water and food. We can help take care of it!', 'sprout'),
            teach('Throw trash in bins', 'Putting trash in the bin keeps parks and beaches clean for everyone!', 'trash'),
            teach('Trees are treasures', 'Trees give us air to breathe and homes for animals. We plant trees to help the Earth!', 'tree'),
          ],
          steps: [
            {
              id: sid('care1'),
              kind: 'choice',
              prompt: 'Where should you throw away trash?',
              say: 'Where should you throw away trash?',
              hint: 'Not on the ground!',
              explain: 'In the trash bin! Clean Earth, happy Earth.',
              options: pictureChoices({ icon: 'trash', caption: 'trash bin' }, [
                { icon: 'hills', caption: 'on the grass' },
                { icon: 'wave', caption: 'in the water' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('care2'),
              kind: 'choice',
              prompt: 'Why are trees important?',
              say: 'Why are trees important for the Earth?',
              hint: 'They give us something we breathe.',
              explain: 'Trees give us fresh air to breathe and homes for animals!',
              options: wordChoices('They give us air', ['They are noisy', 'They eat trash']),
              layout: 'row',
            },
            {
              id: sid('care3'),
              kind: 'choice',
              prompt: 'How can you save water at home?',
              say: 'How can you save water at home?',
              hint: 'Think about brushing your teeth.',
              explain: 'Turning off the tap while brushing saves water every day!',
              options: wordChoices('turn off the tap while brushing', ['leave taps running', 'water the sidewalk']),
              layout: 'row',
            },
            sortStep(
              'Sort: helps the Earth or hurts the Earth!',
              [
                { id: 'good', label: 'Helps Earth', icon: 'sprout', tone: 'grass' },
                { id: 'bad', label: 'Hurts Earth', icon: 'trash', tone: 'coral' },
              ],
              [
                { icon: 'tree', label: 'planting trees', bin: 'good' },
                { icon: 'fire', label: 'littering fires', bin: 'bad' },
                { icon: 'bicycle', label: 'riding bikes', bin: 'good' },
                { icon: 'trash', label: 'dropping trash', bin: 'bad' },
                { icon: 'blossom', label: 'growing flowers', bin: 'good' },
                { icon: 'rock', label: 'throwing rocks at windows', bin: 'bad' },
              ],
              'Small choices add up — planting, biking and cleaning all help our planet!',
            ),
          ],
        },
        {
          id: 'so-traditions',
          title: 'Celebrations Around the World',
          icon: 'party',
          blurb: 'How people celebrate',
          tone: 'grass',
          teach: [
            teach('Everyone celebrates', 'People everywhere celebrate special days with food, music and family. Party time around the world!', 'party'),
            teach('Birthdays everywhere', 'Almost everyone celebrates birthdays — with cakes, candles and songs!', 'cake'),
            teach('Different foods, same joy', 'Celebration foods are different around the world, but the smiles are the same!', 'fireworks'),
          ],
          steps: [
            {
              id: sid('trad1'),
              kind: 'choice',
              prompt: 'What do many people do on birthdays?',
              say: 'What do many people do on birthdays?',
              hint: 'It is sweet and has candles.',
              explain: 'Blow out candles on a birthday cake and make a wish!',
              options: pictureChoices({ icon: 'cake', caption: 'birthday cake' }, [
                { icon: 'snowflake', caption: 'snowballs' },
                { icon: 'rock', caption: 'rocks' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('trad2'),
              kind: 'choice',
              prompt: 'What lights up the sky at big celebrations?',
              say: 'What lights up the night sky at big celebrations?',
              hint: 'They boom and sparkle.',
              explain: 'Fireworks! They sparkle and boom at big celebrations.',
              options: pictureChoices({ icon: 'fireworks', caption: 'fireworks' }, [
                { icon: 'bulb', caption: 'light bulbs' },
                { icon: 'flashlight', caption: 'flashlights' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('trad3'),
              kind: 'choice',
              prompt: 'How are celebrations around the world different and alike?',
              say: 'How are celebrations around the world alike and different?',
              hint: 'Think about food, music and family.',
              explain: 'People celebrate with different foods and music, but everyone celebrates with joy and family!',
              options: wordChoices('Different foods, same joy', ['Nothing is alike', 'Everyone celebrates alone']),
              layout: 'row',
            },
          ],
        },
        {
          id: 'so-past-present',
          title: 'Long Ago & Today',
          icon: 'clock',
          blurb: 'Then and now',
          tone: 'grass',
          teach: [
            teach('Times change!', 'Long ago, kids played with wooden toys and wrote with chalk. Today we have video calls and electric lights!', 'clock'),
            teach('Old and new', 'Grandmas and grandpas were kids long ago! They can tell you all about it.', 'family'),
          ],
          steps: [
            {
              id: sid('past1'),
              kind: 'choice',
              prompt: 'How did people get water long, long ago?',
              say: 'How did people get water long, long ago?',
              hint: 'They carried it from a well or a river.',
              explain: 'People carried buckets of water from wells and rivers. Today it flows from our taps!',
              options: pictureChoices({ icon: 'waterDrop', caption: 'carried from wells' }, [
                { icon: 'phone', caption: 'ordered online' },
                { icon: 'rocket', caption: 'flew to space' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('past2'),
              kind: 'choice',
              prompt: 'Which one is NEW (did not exist long ago)?',
              say: 'Which one is new and did not exist long ago?',
              hint: 'Long ago there were no screens.',
              explain: 'Tablets are new! Long ago people read by candlelight.',
              options: pictureChoices({ icon: 'phone', caption: 'tablet' }, [
                { icon: 'candle', caption: 'candle' },
                { icon: 'horse', caption: 'horse' },
              ]),
              layout: 'grid-3',
            },
            orderStep(
              'Put travel in order: oldest to newest!',
              [
                { icon: 'horse', label: 'riding horses', order: 1 },
                { icon: 'bicycle', label: 'bicycles', order: 2 },
                { icon: 'car', label: 'cars', order: 3 },
                { icon: 'rocket', label: 'rockets to space', order: 4 },
              ],
              'Horses, then bicycles, then cars, then rockets! Travel keeps getting faster.',
            ),
          ],
        },

        {
          id: 'so-needs-wants',
          title: 'Needs & Wants',
          icon: 'gift',
          blurb: 'What we need and what we wish for',
          tone: 'grass',
          teach: [
            teach('Needs and wants', 'Needs are things we must have to live: food, water, clothes, a home. Wants are things we wish for, like toys!', 'gift'),
            teach('Needs come first', 'Before toys and treats, we need food and a warm place to sleep. Needs always come first!', 'apple'),
          ],
          steps: [
            sortStep(
              'Sort: need or want!',
              [
                { id: 'need', label: 'Need', icon: 'waterDrop', tone: 'sky' },
                { id: 'want', label: 'Want', icon: 'star', tone: 'sun' },
              ],
              [
                { icon: 'apple', label: 'food', bin: 'need' },
                { icon: 'teddy', label: 'teddy bear', bin: 'want' },
                { icon: 'coat', label: 'warm coat', bin: 'need' },
                { icon: 'rocket', label: 'toy rocket', bin: 'want' },
                { icon: 'house', label: 'a home', bin: 'need' },
                { icon: 'candy', label: 'candy', bin: 'want' },
              ],
              'Food, water, clothes and shelter are needs. Toys and treats are wants — fun, but not must-haves!',
            ),
            {
              id: sid('nw1'),
              kind: 'choice',
              prompt: 'Which one is a NEED?',
              say: 'Which one is a need, not a want?',
              hint: 'You cannot live without it.',
              explain: 'Water is a need! Every person must drink water to live.',
              options: pictureChoices({ icon: 'waterDrop', caption: 'water' }, [
                { icon: 'ball', caption: 'a new ball' },
                { icon: 'party', caption: 'a party' },
              ]),
              layout: 'grid-3',
            },
            {
              id: sid('nw2'),
              kind: 'choice',
              prompt: 'Why do families save money?',
              say: 'Why do families save money?',
              hint: 'Saving helps pay for needs first.',
              explain: 'Families save so they can pay for needs — food, home, clothes — and sometimes wants too!',
              options: wordChoices('to pay for needs first', ['to lose it', 'to buy only candy']),
              layout: 'row',
            },
          ],
        },
      ],
    },
  ],
}
